// automatically generated by rust-bindgen 0.73.2

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::runtime::AbilityRuntimeResult;
use ohos_sys_opaque_types::napi_env;

/// Defines the AbilityRuntime_NativeAbilityWrapper structure type.
///
///
/// Available since API-level: 26
#[cfg(feature = "api-26")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
#[repr(C)]
#[derive(Debug)]
pub struct AbilityRuntime_NativeAbilityWrapper {
    _unused: [u8; 0],
}
extern "C" {
    /// Get ability instance ID from NativeAbilityWrapper.
    ///
    /// # Arguments
    ///
    /// * `nativeAbilityWrapper` - The native ability wrapper pointer.
    ///
    /// * `buffer` - A pointer to a buffer that receives the instance ID string which is UUID format,
    /// an amount of 37 bytes, 36 chars plus an ending '\0'.
    ///
    /// * `bufferSize` - The length of the buffer, must be at least 37.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the nativeAbilityWrapper or buffer is null,
    /// or the buffer size is less than 37.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetAbilityInstanceId(
        nativeAbilityWrapper: *const AbilityRuntime_NativeAbilityWrapper,
        buffer: *mut ::core::ffi::c_char,
        bufferSize: i32,
    ) -> AbilityRuntimeResult;
    /// Get ability name from NativeAbilityWrapper.
    ///
    /// # Arguments
    ///
    /// * `nativeAbilityWrapper` - The native ability wrapper pointer.
    ///
    /// * `buffer` - A pointer to a buffer that receives the ability name.
    /// Pass nullptr to query the ability name length.
    ///
    /// * `bufferSize` - The length of the buffer. Make sure the buffer has at least one more byte for '\0'.
    ///
    /// * `writeLength` - Outputs the ability name string length.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the nativeAbilityWrapper or writeLength is null,
    /// or the buffer is too small for the ability name.
    /// [`ABILITY_RUNTIME_ERROR_CODE_ABILITY_WRAPPER_INVALID`](crate::runtime::AbilityRuntimeErrorCode::ABILITY_WRAPPER_INVALID) if the native ability wrapper is invalid or
    /// incomplete.
    /// [`ABILITY_RUNTIME_ERROR_CODE_INTERNAL`](crate::runtime::AbilityRuntimeErrorCode::INTERNAL) inner error.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetAbilityName(
        nativeAbilityWrapper: *const AbilityRuntime_NativeAbilityWrapper,
        buffer: *mut ::core::ffi::c_char,
        bufferSize: i32,
        writeLength: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get napi_env from NativeAbilityWrapper.
    ///
    /// # Arguments
    ///
    /// * `nativeAbilityWrapper` - The native ability wrapper pointer.
    ///
    /// * `env` - A pointer to the receive napi_env value. napi_env is valid until the process terminates.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the nativeAbilityWrapper or env is null.
    /// [`ABILITY_RUNTIME_ERROR_CODE_ABILITY_WRAPPER_INVALID`](crate::runtime::AbilityRuntimeErrorCode::ABILITY_WRAPPER_INVALID) if the native ability wrapper is invalid or
    /// incomplete.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetEnv(
        nativeAbilityWrapper: *const AbilityRuntime_NativeAbilityWrapper,
        env: *mut napi_env,
    ) -> AbilityRuntimeResult;
}
