// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::common::{CryptoResult, Crypto_DataBlob};

/// Define the key pair structure.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
pub struct OH_CryptoKeyPair {
    _unused: [u8; 0],
}
/// Define the public key structure.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
pub struct OH_CryptoPubKey {
    _unused: [u8; 0],
}
/// Defines the private key structure.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[repr(C)]
pub struct OH_CryptoPrivKey {
    _unused: [u8; 0],
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl CryptoAsymKey_ParamType {
    /// Indicates the DSA prime p.
    pub const CRYPTO_DSA_P_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(101);
    /// Indicates the DSA sub-prime q.
    pub const CRYPTO_DSA_Q_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(102);
    /// Indicates the DSA base g.
    pub const CRYPTO_DSA_G_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(103);
    /// Indicates the DSA private key.
    pub const CRYPTO_DSA_SK_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(104);
    /// Indicates the DSA public key.
    pub const CRYPTO_DSA_PK_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(105);
    /// Indicates the prime p of an elliptic curve (EC) prime finite field.
    pub const CRYPTO_ECC_FP_P_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(201);
    /// Indicates the first coefficient a of this elliptic curve.
    pub const CRYPTO_ECC_A_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(202);
    /// Indicates the second coefficient b of this elliptic curve.
    pub const CRYPTO_ECC_B_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(203);
    /// Indicates the affine x-coordinate of base point g.
    pub const CRYPTO_ECC_G_X_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(204);
    /// Indicates the affine y-coordinate of base point g.
    pub const CRYPTO_ECC_G_Y_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(205);
    /// Indicates the order of the base point g.
    pub const CRYPTO_ECC_N_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(206);
    /// Indicates the cofactor of the elliptic curve.
    pub const CRYPTO_ECC_H_INT: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(207);
    /// Indicates the private value of the ECC private key.
    pub const CRYPTO_ECC_SK_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(208);
    /// Indicates the affine x-coordinate of a point, which is the public point of an ECC public key.
    pub const CRYPTO_ECC_PK_X_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(209);
    /// Indicates the affine y-coordinate of a point, which is the public point of an ECC public key.
    pub const CRYPTO_ECC_PK_Y_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(210);
    /// Indicates an elliptic curve finite field type.
    pub const CRYPTO_ECC_FIELD_TYPE_STR: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(211);
    /// Indicates the field size in bits.
    pub const CRYPTO_ECC_FIELD_SIZE_INT: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(212);
    /// Indicates the curve name according to SECG (Standards for Efficient Cryptography Group).
    pub const CRYPTO_ECC_CURVE_NAME_STR: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(213);
    /// Indicates the modulus n of RSA algorithm.
    pub const CRYPTO_RSA_N_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(301);
    /// Indicates the private exponent d of RSA algorithm.
    pub const CRYPTO_RSA_D_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(302);
    /// Indicates the public exponent e of RSA algorithm.
    pub const CRYPTO_RSA_E_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(303);
    /// Indicates the prime p of DH algorithm.
    pub const CRYPTO_DH_P_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(401);
    /// Indicates the generator g of DH algorithm.
    pub const CRYPTO_DH_G_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(402);
    /// Indicates the number of bits of the private key length used in the DH algorithm.
    pub const CRYPTO_DH_L_INT: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(403);
    /// Indicates the private value of the DH private key.
    pub const CRYPTO_DH_SK_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(404);
    /// Indicates the public value of the DH public key.
    pub const CRYPTO_DH_PK_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(405);
    /// Indicates the private value of the ED25519 private key.
    pub const CRYPTO_ED25519_SK_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(501);
    /// Indicates the public value of the ED25519 public key.
    pub const CRYPTO_ED25519_PK_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(502);
    /// Indicates the private value of the X25519 private key.
    pub const CRYPTO_X25519_SK_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(601);
    /// Indicates the public value of the X25519 public key.
    pub const CRYPTO_X25519_PK_DATABLOB: CryptoAsymKey_ParamType = CryptoAsymKey_ParamType(602);
}
#[repr(transparent)]
/// Define the asymmetric key parameter types.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CryptoAsymKey_ParamType(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl Crypto_EncodingType {
    /// PEM format
    pub const CRYPTO_PEM: Crypto_EncodingType = Crypto_EncodingType(0);
    /// DER format
    pub const CRYPTO_DER: Crypto_EncodingType = Crypto_EncodingType(1);
}
#[repr(transparent)]
/// Define the encoding type.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct Crypto_EncodingType(pub ::core::ffi::c_uint);
/// Define the asymmetric key generator structure.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
pub struct OH_CryptoAsymKeyGenerator {
    _unused: [u8; 0],
}
/// Defines the private key encoding params structure.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[repr(C)]
pub struct OH_CryptoPrivKeyEncodingParams {
    _unused: [u8; 0],
}
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
impl CryptoPrivKeyEncoding_ParamType {
    /// Indicates the password string.
    pub const CRYPTO_PRIVATE_KEY_ENCODING_PASSWORD_STR: CryptoPrivKeyEncoding_ParamType =
        CryptoPrivKeyEncoding_ParamType(0);
    /// Indicates the symmetric cipher string.
    pub const CRYPTO_PRIVATE_KEY_ENCODING_SYMMETRIC_CIPHER_STR: CryptoPrivKeyEncoding_ParamType =
        CryptoPrivKeyEncoding_ParamType(1);
}
#[repr(transparent)]
/// Defines the private key encoding param type.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CryptoPrivKeyEncoding_ParamType(pub ::core::ffi::c_uint);
/// Defines the asymmetric key spec structure.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[repr(C)]
pub struct OH_CryptoAsymKeySpec {
    _unused: [u8; 0],
}
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
impl CryptoAsymKeySpec_Type {
    /// Common parameters spec.
    pub const CRYPTO_ASYM_KEY_COMMON_PARAMS_SPEC: CryptoAsymKeySpec_Type =
        CryptoAsymKeySpec_Type(0);
    /// Private key spec.
    pub const CRYPTO_ASYM_KEY_PRIVATE_KEY_SPEC: CryptoAsymKeySpec_Type = CryptoAsymKeySpec_Type(1);
    /// Public key spec.
    pub const CRYPTO_ASYM_KEY_PUBLIC_KEY_SPEC: CryptoAsymKeySpec_Type = CryptoAsymKeySpec_Type(2);
    /// Key pair spec.
    pub const CRYPTO_ASYM_KEY_KEY_PAIR_SPEC: CryptoAsymKeySpec_Type = CryptoAsymKeySpec_Type(3);
}
#[repr(transparent)]
/// Defines the asymmetric key spec type.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CryptoAsymKeySpec_Type(pub ::core::ffi::c_uint);
/// Defines the asymmetric key generator with spec.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[repr(C)]
pub struct OH_CryptoAsymKeyGeneratorWithSpec {
    _unused: [u8; 0],
}
/// Defines the EC point structure.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[repr(C)]
pub struct OH_CryptoEcPoint {
    _unused: [u8; 0],
}
extern "C" {
    /// Create an asymmetric key generator according to the given algorithm name.
    ///
    /// # Arguments
    ///
    /// * `algoName` - Indicates the algorithm name for generating the generator. Example RSA1024|PRIMES_2.
    ///
    /// * `ctx` - Indicates the pointer to asymmetric key generator context.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_INVALID_PARAMS`] 401 - If parameter is invalid.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto opertion failed.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CryptoAsymKeyGenerator_Create(
        algoName: *const ::core::ffi::c_char,
        ctx: *mut *mut OH_CryptoAsymKeyGenerator,
    ) -> CryptoResult;
    /// Generate an asymmetric key(a key pair).
    ///
    /// # Arguments
    ///
    /// * `ctx` - Indicates the asymmetric key generator context.
    ///
    /// * `keyCtx` - Indicates the pointer to the asyKey context.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_INVALID_PARAMS`] 401 - If parameter is invalid.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto opertion failed.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CryptoAsymKeyGenerator_Generate(
        ctx: *mut OH_CryptoAsymKeyGenerator,
        keyCtx: *mut *mut OH_CryptoKeyPair,
    ) -> CryptoResult;
    /// Convert the asymmetric key data to a key pair.
    ///
    /// # Arguments
    ///
    /// * `ctx` - Indicates the asymmetric key generator context.
    ///
    /// * `type` - Indicates the encryption encoding type.
    ///
    /// * `pubKeyData` - Indicates the public key data.
    ///
    /// * `priKeyData` - Indicates the private key data.
    ///
    /// * `keyCtx` - Indicates the pointer to the keyPair instance.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_INVALID_PARAMS`] 401 - If parameter is invalid.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto opertion failed.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CryptoAsymKeyGenerator_Convert(
        ctx: *mut OH_CryptoAsymKeyGenerator,
        type_: Crypto_EncodingType,
        pubKeyData: *mut Crypto_DataBlob,
        priKeyData: *mut Crypto_DataBlob,
        keyCtx: *mut *mut OH_CryptoKeyPair,
    ) -> CryptoResult;
    /// Get the algorithm name of the asymmetric key generator.
    ///
    /// # Arguments
    ///
    /// * `ctx` - Indicates the asymmetric key generator context.
    ///
    /// # Returns
    ///
    /// * Returns the asymmetric key algorithm name.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CryptoAsymKeyGenerator_GetAlgoName(
        ctx: *mut OH_CryptoAsymKeyGenerator,
    ) -> *const ::core::ffi::c_char;
    /// Destroy the asymmetric key generator.
    ///
    /// # Arguments
    ///
    /// * `ctx` - Indicates the asymmetric key generator context.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CryptoAsymKeyGenerator_Destroy(ctx: *mut OH_CryptoAsymKeyGenerator);
    /// Destroy the key pair.
    ///
    /// # Arguments
    ///
    /// * `keyCtx` - Indicates the keyPair context.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CryptoKeyPair_Destroy(keyCtx: *mut OH_CryptoKeyPair);
    /// Get the public key of the key pair.
    ///
    /// # Arguments
    ///
    /// * `keyCtx` - Indicates the keyPair context.
    ///
    /// # Returns
    ///
    /// * Return the public key context from the key pair.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CryptoKeyPair_GetPubKey(keyCtx: *mut OH_CryptoKeyPair) -> *mut OH_CryptoPubKey;
    /// Gets the private key of the key pair.
    ///
    /// # Arguments
    ///
    /// * `keyCtx` - Indicates the keyPair context.
    ///
    /// # Returns
    ///
    /// * Return the private key context from the key pair.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoKeyPair_GetPrivKey(keyCtx: *mut OH_CryptoKeyPair) -> *mut OH_CryptoPrivKey;
    /// Encode the public key.
    ///
    /// # Arguments
    ///
    /// * `key` - Indicates the public key.
    ///
    /// * `type` - Indicates the pubkey type.
    ///
    /// * `encodingStandard` - Indicates the encoding standard.
    ///
    /// * `out` - Indicates the encoded result.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_INVALID_PARAMS`] 401 - If parameter is invalid.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto opertion failed.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CryptoPubKey_Encode(
        key: *mut OH_CryptoPubKey,
        type_: Crypto_EncodingType,
        encodingStandard: *const ::core::ffi::c_char,
        out: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Get the specified param of the public key.
    ///
    /// # Arguments
    ///
    /// * `key` - Indicates the public key.
    ///
    /// * `item` - Indicates the asymmetric key param type.
    ///
    /// * `value` - Indicates the output data.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_INVALID_PARAMS`] 401 - If parameter is invalid.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto opertion failed.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_CryptoPubKey_GetParam(
        key: *mut OH_CryptoPubKey,
        item: CryptoAsymKey_ParamType,
        value: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Sets the password to the asymmetric key generator context.
    ///
    /// Call this method to set the password if you need to convert encrypted private key data to a key pair using
    /// [`OH_CryptoAsymKeyGenerator_Convert`].
    ///
    ///
    /// # Arguments
    ///
    /// * `ctx` - Indicates the asymmetric key generator context.
    ///
    /// * `password` - Indicates the password.
    ///
    /// * `passwordLen` - Indicates the password length.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeyGenerator_SetPassword(
        ctx: *mut OH_CryptoAsymKeyGenerator,
        password: *const ::core::ffi::c_uchar,
        passwordLen: u32,
    ) -> CryptoResult;
    /// Creates private key encoding params.
    ///
    /// # Arguments
    ///
    /// * `ctx` - Indicates the private key encoding params.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoPrivKeyEncodingParams_Create(
        ctx: *mut *mut OH_CryptoPrivKeyEncodingParams,
    ) -> CryptoResult;
    /// Sets the private key encoding params.
    ///
    /// # Arguments
    ///
    /// * `ctx` - Indicates the private key encoding params.
    ///
    /// * `type` - Indicates the private key encoding param type.
    ///
    /// * `value` - Indicates the private key encoding params value.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoPrivKeyEncodingParams_SetParam(
        ctx: *mut OH_CryptoPrivKeyEncodingParams,
        type_: CryptoPrivKeyEncoding_ParamType,
        value: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Destroys the private key encoding params.
    ///
    /// # Arguments
    ///
    /// * `ctx` - Indicates the private key encoding params.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoPrivKeyEncodingParams_Destroy(ctx: *mut OH_CryptoPrivKeyEncodingParams);
    /// Encodes the private key.
    ///
    /// # Arguments
    ///
    /// * `key` - Indicates the private key.
    ///
    /// * `type` - Indicates the private encoding type.
    ///
    /// * `encodingStandard` - Indicates the encoding standard, such as "PKCS8".
    ///
    /// * `params` - Indicates the private key encoding params, it can be NULL, and if you want encypt the private key,
    /// you should set this param.
    ///
    /// * `out` - Indicates the encoded result.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoPrivKey_Encode(
        key: *mut OH_CryptoPrivKey,
        type_: Crypto_EncodingType,
        encodingStandard: *const ::core::ffi::c_char,
        params: *mut OH_CryptoPrivKeyEncodingParams,
        out: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Gets the specified param of the private key.
    ///
    /// # Arguments
    ///
    /// * `key` - Indicates the private key.
    ///
    /// * `item` - Indicates the asymmetric key param type.
    ///
    /// * `value` - Indicates the output data.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoPrivKey_GetParam(
        key: *mut OH_CryptoPrivKey,
        item: CryptoAsymKey_ParamType,
        value: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Generates an EC common parameters spec.
    ///
    /// # Arguments
    ///
    /// * `curveName` - Indicates the ECC curve name.
    ///
    /// * `spec` - Indicates the pointer to the EC common parameters spec.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeySpec_GenEcCommonParamsSpec(
        curveName: *const ::core::ffi::c_char,
        spec: *mut *mut OH_CryptoAsymKeySpec,
    ) -> CryptoResult;
    /// Generates a DH common parameters spec.
    ///
    /// # Arguments
    ///
    /// * `pLen` - Indicates the byte length of the prime p.
    ///
    /// * `skLen` - Indicates the byte length of the private key.
    ///
    /// * `spec` - Indicates the pointer to the DH common parameters spec.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeySpec_GenDhCommonParamsSpec(
        pLen: ::core::ffi::c_int,
        skLen: ::core::ffi::c_int,
        spec: *mut *mut OH_CryptoAsymKeySpec,
    ) -> CryptoResult;
    /// Creates an asymmetric key spec according to the given algorithm name and spec type.
    ///
    /// # Arguments
    ///
    /// * `algoName` - Indicates the algorithm name for generating the spec. Example RSA.
    ///
    /// * `type` - Indicates the asymmetric key spec type.
    ///
    /// * `spec` - Indicates the pointer to the asymmetric key spec.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeySpec_Create(
        algoName: *const ::core::ffi::c_char,
        type_: CryptoAsymKeySpec_Type,
        spec: *mut *mut OH_CryptoAsymKeySpec,
    ) -> CryptoResult;
    /// Sets the specified parameter to the asymmetric key spec.
    ///
    /// # Arguments
    ///
    /// * `spec` - Indicates the asymmetric key spec.
    ///
    /// * `type` - Indicates the asymmetric key param type.
    ///
    /// * `value` - Indicates the input data.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeySpec_SetParam(
        spec: *mut OH_CryptoAsymKeySpec,
        type_: CryptoAsymKey_ParamType,
        value: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Sets the common parameters spec to the asymmetric key spec.
    ///
    /// # Arguments
    ///
    /// * `spec` - Indicates the asymmetric key spec.
    ///
    /// * `commonParamsSpec` - Indicates the common parameters spec.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeySpec_SetCommonParamsSpec(
        spec: *mut OH_CryptoAsymKeySpec,
        commonParamsSpec: *mut OH_CryptoAsymKeySpec,
    ) -> CryptoResult;
    /// Gets the specified parameter from the asymmetric key spec.
    ///
    /// # Arguments
    ///
    /// * `spec` - Indicates the asymmetric key spec.
    ///
    /// * `type` - Indicates the asymmetric key param type.
    ///
    /// * `value` - Indicates the output data.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeySpec_GetParam(
        spec: *mut OH_CryptoAsymKeySpec,
        type_: CryptoAsymKey_ParamType,
        value: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Destroys the asymmetric key spec.
    ///
    /// # Arguments
    ///
    /// * `spec` - Indicates the asymmetric key spec.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeySpec_Destroy(spec: *mut OH_CryptoAsymKeySpec);
    /// Creates an asymmetric key generator with spec.
    ///
    /// # Arguments
    ///
    /// * `keySpec` - Indicates the asymmetric key spec.
    ///
    /// * `generator` - Indicates the asymmetric key generator with spec.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeyGeneratorWithSpec_Create(
        keySpec: *mut OH_CryptoAsymKeySpec,
        generator: *mut *mut OH_CryptoAsymKeyGeneratorWithSpec,
    ) -> CryptoResult;
    /// Generates a key pair according to the asymmetric key spec.
    ///
    /// # Arguments
    ///
    /// * `generator` - Indicates the asymmetric key generator with spec.
    ///
    /// * `keyPair` - Indicates the pointer to the key pair.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeyGeneratorWithSpec_GenKeyPair(
        generator: *mut OH_CryptoAsymKeyGeneratorWithSpec,
        keyPair: *mut *mut OH_CryptoKeyPair,
    ) -> CryptoResult;
    /// Destroys the asymmetric key generator with spec.
    ///
    /// # Arguments
    ///
    /// * `generator` - Indicates the asymmetric key generator with spec.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoAsymKeyGeneratorWithSpec_Destroy(
        generator: *mut OH_CryptoAsymKeyGeneratorWithSpec,
    );
    /// Creates an EC point.
    ///
    /// # Arguments
    ///
    /// * `curveName` - Indicates the curve name.
    ///
    /// * `ecKeyData` - Indicates the EC point data, supports "04 || x || y", "02 || x" or "03 || x" format.
    /// If ecKeyData param is NULL, an empty EC point spec will be created.
    ///
    /// * `point` - Indicates the pointer to the EC point.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoEcPoint_Create(
        curveName: *const ::core::ffi::c_char,
        ecKeyData: *mut Crypto_DataBlob,
        point: *mut *mut OH_CryptoEcPoint,
    ) -> CryptoResult;
    /// Gets the x and y coordinate of the EC point.
    ///
    /// # Arguments
    ///
    /// * `point` - Indicates the EC point.
    ///
    /// * `x` - Indicates the x coordinate of the EC point, it can be NULL.
    ///
    /// * `y` - Indicates the y coordinate of the EC point, it can be NULL.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoEcPoint_GetCoordinate(
        point: *mut OH_CryptoEcPoint,
        x: *mut Crypto_DataBlob,
        y: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Sets the x and y coordinate to the EC point.
    ///
    /// # Arguments
    ///
    /// * `point` - Indicates the EC point.
    ///
    /// * `x` - Indicates the x coordinate of the EC point.
    ///
    /// * `y` - Indicates the y coordinate of the EC point.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoEcPoint_SetCoordinate(
        point: *mut OH_CryptoEcPoint,
        x: *mut Crypto_DataBlob,
        y: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Encodes the EC point to the specified format.
    ///
    /// # Arguments
    ///
    /// * `point` - Indicates the EC point.
    ///
    /// * `format` - Indicates the encoding format, supports "UNCOMPRESSED" and "COMPRESSED".
    ///
    /// * `out` - Indicates the encoded ec point data.
    ///
    /// # Returns
    ///
    /// * [`OH_Crypto_ErrCode#CRYPTO_SUCCESS`] 0 - If the operation is successful.
    /// [`OH_Crypto_ErrCode#CRYPTO_NOT_SUPPORTED`] 801 - If the operation is not supported.
    /// [`OH_Crypto_ErrCode#CRYPTO_MEMORY_ERROR`] 17620001 - If memory operation failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_PARAMETER_CHECK_FAILED`] 17620003 - If parameter check failed.
    /// [`OH_Crypto_ErrCode#CRYPTO_OPERTION_ERROR`] 17630001 - If crypto operation failed.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoEcPoint_Encode(
        point: *mut OH_CryptoEcPoint,
        format: *const ::core::ffi::c_char,
        out: *mut Crypto_DataBlob,
    ) -> CryptoResult;
    /// Destroys the EC point.
    ///
    /// # Arguments
    ///
    /// * `point` - Indicates the EC point.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_CryptoEcPoint_Destroy(point: *mut OH_CryptoEcPoint);
}
