// automatically generated by rust-bindgen 0.73.2

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(deprecated)]
#[allow(unused_imports)]
use crate::averrors::OH_AVErrCode;

/// The struct initializes an AVTranscoder.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[repr(C)]
#[derive(Debug)]
pub struct OH_AVTranscoder {
    _unused: [u8; 0],
}
/// The struct initializes an AVTranscoder_Config.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[repr(C)]
#[derive(Debug)]
pub struct OH_AVTranscoder_Config {
    _unused: [u8; 0],
}
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
impl OH_AVTranscoder_State {
    /// The transcoding process is prepared and ready to start.
    pub const AVTRANSCODER_PREPARED: OH_AVTranscoder_State = OH_AVTranscoder_State(1);
    /// The transcoding process has started.
    pub const AVTRANSCODER_STARTED: OH_AVTranscoder_State = OH_AVTranscoder_State(2);
    /// The transcoding process is paused.
    pub const AVTRANSCODER_PAUSED: OH_AVTranscoder_State = OH_AVTranscoder_State(3);
    /// The transcoding process has been canceled.
    pub const AVTRANSCODER_CANCELLED: OH_AVTranscoder_State = OH_AVTranscoder_State(4);
    /// The transcoding process is completed.
    pub const AVTRANSCODER_COMPLETED: OH_AVTranscoder_State = OH_AVTranscoder_State(5);
}
#[repr(transparent)]
/// Enumerates the transcoding states.
///
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AVTranscoder_State(pub ::core::ffi::c_uint);
/// Defines a callback invoked when the state of the transcoding process changes.
///
/// # Arguments
///
/// * `transcoder` - The pointer to an OH_AVTranscoder instance.
///
/// * `state` - Indicates the transcoder state. For details, see [`OH_AVTranscoder_State`](crate::avtranscoder_base::OH_AVTranscoder_State).
///
/// * `userData` - Pointer to user specific data.
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
pub type OH_AVTranscoder_OnStateChange = ::core::option::Option<
    unsafe extern "C" fn(
        transcoder: *mut OH_AVTranscoder,
        state: OH_AVTranscoder_State,
        userData: *mut ::core::ffi::c_void,
    ),
>;
/// Defines a callback invoked when an error occurs during the transcoding process.
///
/// # Arguments
///
/// * `transcoder` - Pointer to an OH_AVTranscoder instance.
///
/// * `errorCode` - Error code.
/// [`AV_ERR_NO_MEMORY`](crate::averrors::OH_AVErrCode::AV_ERR_NO_MEMORY): memory is insufficient.
/// [`AV_ERR_IO`](crate::averrors::OH_AVErrCode::AV_ERR_IO): IO access failed.
/// [`AV_ERR_INVALID_STATE`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_STATE): current state does not support this operation.
/// [`AV_ERR_UNSUPPORT`](crate::averrors::OH_AVErrCode::AV_ERR_UNSUPPORT): unsupported function.
/// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): the parameter check failed.
/// [`AV_ERR_OPERATE_NOT_PERMIT`](crate::averrors::OH_AVErrCode::AV_ERR_OPERATE_NOT_PERMIT): operation not allowed.
///
/// * `errorMsg` - Error message.
///
/// * `userData` - Pointer to user specific data.
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
pub type OH_AVTranscoder_OnError = ::core::option::Option<
    unsafe extern "C" fn(
        transcoder: *mut OH_AVTranscoder,
        errorCode: i32,
        errorMsg: *const ::core::ffi::c_char,
        userData: *mut ::core::ffi::c_void,
    ),
>;
/// Defines a callback invoked when the progress of the transcoding process is updated.
///
/// # Arguments
///
/// * `transcoder` - Pointer to an OH_AVTranscoder instance.
///
/// * `progress` - Transcoding progress, in percentage.
///
/// * `userData` - Pointer to user specific data.
///
/// Available since API-level: 20
#[cfg(feature = "api-20")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
pub type OH_AVTranscoder_OnProgressUpdate = ::core::option::Option<
    unsafe extern "C" fn(
        transcoder: *mut OH_AVTranscoder,
        progress: i32,
        userData: *mut ::core::ffi::c_void,
    ),
>;
