/* automatically generated by rust-bindgen 0.69.4 */

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::drawing::types::*;

extern "C" {
    /** @brief Creates an <b>OH_Drawing_Matrix</b> object.

    @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
    @return Returns the pointer to the <b>OH_Drawing_Matrix</b> object created.
    @since 11
    @version 1.0*/
    pub fn OH_Drawing_MatrixCreate() -> *mut OH_Drawing_Matrix;
    /** @brief Sets the params for a matrix.

    @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
    @param OH_Drawing_Matrix Indicates the pointer to an <b>OH_Drawing_Matrix</b> object.
    @param scaleX  horizontal scale factor to store
    @param skewX   horizontal skew factor to store
    @param transX  horizontal translation to store
    @param skewY   vertical skew factor to store
    @param scaleY  vertical scale factor to store
    @param transY  vertical translation to store
    @param persp0  input x-axis values perspective factor to store
    @param persp1  input y-axis values perspective factor to store
    @param persp2  perspective scale factor to store
    @since 11
    @version 1.0*/
    pub fn OH_Drawing_MatrixSetMatrix(
        arg1: *mut OH_Drawing_Matrix,
        scaleX: f32,
        skewX: f32,
        transX: f32,
        skewY: f32,
        scaleY: f32,
        transY: f32,
        persp0: f32,
        persp1: f32,
        persp2: f32,
    );
    /** @brief Destroys an <b>OH_Drawing_Matrix</b> object and reclaims the memory occupied by the object.

    @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
    @param OH_Drawing_Matrix Indicates the pointer to an <b>OH_Drawing_Matrix</b> object.
    @since 11
    @version 1.0*/
    pub fn OH_Drawing_MatrixDestroy(arg1: *mut OH_Drawing_Matrix);
}
