// automatically generated by rust-bindgen 0.73.2

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage> {
    storage: Storage,
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    pub const fn new(storage: Storage) -> Self {
        Self { storage }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    #[inline]
    fn extract_bit(byte: u8, index: usize) -> bool {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        byte & mask == mask
    }
    #[inline]
    pub fn get_bit(&self, index: usize) -> bool {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = self.storage.as_ref()[byte_index];
        Self::extract_bit(byte, index)
    }
    #[inline]
    pub unsafe fn raw_get_bit(this: *const Self, index: usize) -> bool {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize)
        };
        Self::extract_bit(byte, index)
    }
    #[inline]
    fn change_bit(byte: u8, index: usize, val: bool) -> u8 {
        let bit_index = if cfg!(target_endian = "big") {
            7 - (index % 8)
        } else {
            index % 8
        };
        let mask = 1 << bit_index;
        if val {
            byte | mask
        } else {
            byte & !mask
        }
    }
    #[inline]
    pub fn set_bit(&mut self, index: usize, val: bool) {
        debug_assert!(index / 8 < self.storage.as_ref().len());
        let byte_index = index / 8;
        let byte = &mut self.storage.as_mut()[byte_index];
        *byte = Self::change_bit(*byte, index, val);
    }
    #[inline]
    pub unsafe fn raw_set_bit(this: *mut Self, index: usize, val: bool) {
        debug_assert!(index / 8 < core::mem::size_of::<Storage>());
        let byte_index = index / 8;
        let byte = unsafe {
            (core::ptr::addr_of_mut!((*this).storage) as *mut u8).offset(byte_index as isize)
        };
        unsafe { *byte = Self::change_bit(*byte, index, val) };
    }
    #[inline]
    pub fn get(&self, bit_offset: usize, bit_width: u8) -> u64 {
        let Self { storage } = self;
        let storage = storage.as_ref();
        unsafe { Self::get_bits(storage.as_ptr(), storage.len(), bit_offset, bit_width) }
    }
    #[inline]
    pub unsafe fn raw_get(this: *const Self, bit_offset: usize, bit_width: u8) -> u64 {
        unsafe {
            Self::get_bits(
                core::ptr::addr_of!((*this).storage).cast(),
                core::mem::size_of::<Storage>(),
                bit_offset,
                bit_width,
            )
        }
    }
    #[inline]
    pub fn set(&mut self, bit_offset: usize, bit_width: u8, val: u64) {
        let Self { storage } = self;
        let storage = storage.as_mut();
        unsafe {
            Self::set_bits(
                storage.as_mut_ptr(),
                storage.len(),
                bit_offset,
                bit_width,
                val,
            );
        }
    }
    #[inline]
    pub unsafe fn raw_set(this: *mut Self, bit_offset: usize, bit_width: u8, val: u64) {
        unsafe {
            Self::set_bits(
                core::ptr::addr_of_mut!((*this).storage).cast(),
                core::mem::size_of::<Storage>(),
                bit_offset,
                bit_width,
                val,
            );
        }
    }
}
impl<Storage> __BindgenBitfieldUnit<Storage> {
    #[inline]
    const fn field_layout(
        storage_len: usize,
        bit_offset: usize,
        bit_width: u8,
    ) -> (usize, usize, usize) {
        debug_assert!(bit_width <= 64);
        let start_byte = bit_offset / 8;
        let bit_shift = bit_offset % 8;
        debug_assert!(start_byte < storage_len);
        let bytes_needed = (bit_width as usize + bit_shift + 7) / 8;
        assert!(start_byte + bytes_needed <= storage_len);
        (start_byte, bit_shift, bytes_needed)
    }
    #[inline]
    const unsafe fn get_bits(
        storage: *const u8,
        storage_len: usize,
        bit_offset: usize,
        bit_width: u8,
    ) -> u64 {
        let (start_byte, bit_shift, bytes_needed) =
            Self::field_layout(storage_len, bit_offset, bit_width);
        if bit_width == 0 {
            return 0;
        }
        let mut val = 0u64;
        let mut i = 0;
        while i < bytes_needed && i < 8 {
            let byte = unsafe { *storage.add(start_byte + i) };
            let byte = if cfg!(target_endian = "big") {
                byte.reverse_bits()
            } else {
                byte
            };
            val |= (byte as u64) << (i * 8);
            i += 1;
        }
        val >>= bit_shift;
        if bytes_needed == 9 {
            let byte = unsafe { *storage.add(start_byte + 8) };
            let byte = if cfg!(target_endian = "big") {
                byte.reverse_bits()
            } else {
                byte
            };
            val |= (byte as u64) << (64 - bit_shift);
        }
        if bit_width < 64 {
            val &= (1u64 << bit_width) - 1;
        }
        if cfg!(target_endian = "big") {
            val = val.reverse_bits() >> (64 - bit_width as usize);
        }
        val
    }
    #[inline]
    unsafe fn set_bits(
        storage: *mut u8,
        storage_len: usize,
        bit_offset: usize,
        bit_width: u8,
        mut val: u64,
    ) {
        let (start_byte, bit_shift, bytes_needed) =
            Self::field_layout(storage_len, bit_offset, bit_width);
        if bit_width == 0 {
            return;
        }
        if bit_width == 64 && bit_shift == 0 {
            unsafe { storage.add(start_byte).cast::<u64>().write_unaligned(val) };
            return;
        }
        let field_mask = if bit_width == 64 {
            !0u64
        } else {
            (1u64 << bit_width) - 1
        };
        val &= field_mask;
        if cfg!(target_endian = "big") {
            val = val.reverse_bits() >> (64 - bit_width as usize);
        }
        if bytes_needed == 9 {
            let shift = 64 - bit_shift;
            unsafe {
                Self::set_byte(
                    storage.add(start_byte + 8),
                    (val >> shift) as u8,
                    (field_mask >> shift) as u8,
                );
            }
        }
        let val = val << bit_shift;
        let field_mask = field_mask << bit_shift;
        for i in 0..bytes_needed.min(8) {
            unsafe {
                Self::set_byte(
                    storage.add(start_byte + i),
                    (val >> (i * 8)) as u8,
                    (field_mask >> (i * 8)) as u8,
                );
            }
        }
    }
    #[inline]
    unsafe fn set_byte(byte: *mut u8, val: u8, mask: u8) {
        let (val, mask) = if cfg!(target_endian = "big") {
            (val.reverse_bits(), mask.reverse_bits())
        } else {
            (val, mask)
        };
        unsafe { *byte = (*byte & !mask) | (val & mask) };
    }
}
/// Const-generic methods for bitfield access when offset and width are known
/// at compile time. Inlining exposes these constants to the shared implementation.
impl<const N: usize> __BindgenBitfieldUnit<[u8; N]> {
    /// Get a field using const generics for compile-time optimization.
    #[inline]
    pub const fn get_const<const BIT_OFFSET: usize, const BIT_WIDTH: u8>(&self) -> u64 {
        let Self { storage } = self;
        unsafe { Self::get_bits(storage.as_ptr(), N, BIT_OFFSET, BIT_WIDTH) }
    }
    /// Set a field using const generics for compile-time optimization.
    #[inline]
    pub fn set_const<const BIT_OFFSET: usize, const BIT_WIDTH: u8>(&mut self, val: u64) {
        self.set(BIT_OFFSET, BIT_WIDTH, val);
    }
    /// Raw pointer get using const generics for compile-time optimization.
    #[inline]
    pub const unsafe fn raw_get_const<const BIT_OFFSET: usize, const BIT_WIDTH: u8>(
        this: *const Self,
    ) -> u64 {
        unsafe {
            Self::get_bits(
                core::ptr::addr_of!((*this).storage).cast(),
                N,
                BIT_OFFSET,
                BIT_WIDTH,
            )
        }
    }
    /// Raw pointer set using const generics for compile-time optimization.
    #[inline]
    pub unsafe fn raw_set_const<const BIT_OFFSET: usize, const BIT_WIDTH: u8>(
        this: *mut Self,
        val: u64,
    ) {
        unsafe { Self::raw_set(this, BIT_OFFSET, BIT_WIDTH, val) };
    }
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl HiTraceId_Valid {
    /// Invalid **HiTraceId**.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_ID_INVALID: HiTraceId_Valid = HiTraceId_Valid(0);
    /// Valid **HiTraceId**.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_ID_VALID: HiTraceId_Valid = HiTraceId_Valid(1);
}
#[repr(transparent)]
/// Enumerates whether a **HiTraceId** instance is valid.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct HiTraceId_Valid(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl HiTrace_Version {
    /// Version 1.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_VER_1: HiTrace_Version = HiTrace_Version(0);
}
#[repr(transparent)]
/// Enumerates the HiTrace versions.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct HiTrace_Version(pub ::core::ffi::c_uint);
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl HiTrace_Flag {
    /// Default flag.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_FLAG_DEFAULT: HiTrace_Flag = HiTrace_Flag(0);
    /// Asynchronous call flag.When this flag is set, both synchronous and asynchronous calls are traced.By
    /// default, only synchronous calls are traced.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_FLAG_INCLUDE_ASYNC: HiTrace_Flag = HiTrace_Flag(1);
    /// No span flag.When this flag is set, no span information is created. By default, span information is
    /// created.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_FLAG_DONOT_CREATE_SPAN: HiTrace_Flag = HiTrace_Flag(2);
    /// Trace point flag.When this flag is set in the debugging scenario, the HiLog logs of the trace point are
    /// printed upon calling the **OH_HiTrace_Tracepoint()** API. By default, the HiLog logs are not printed.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_FLAG_TP_INFO: HiTrace_Flag = HiTrace_Flag(4);
    /// No begin and end flag.When this flag is set in the debugging scenario, the HiLog logs about the begin and
    /// end of tracing are printed when the **OH_HiTrace_BeginChain()** and **OH_HiTrace_EndChain()** APIs are called.
    /// By default,the HiLog logs about the begin and end of tracing are not printed.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_FLAG_NO_BE_INFO: HiTrace_Flag = HiTrace_Flag(8);
    /// Log association flag.When this flag is set, the **HiTraceId** information is not added to the HiLog logs.
    /// By default, the **HiTraceId** information is added to the HiLog logs.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_FLAG_DONOT_ENABLE_LOG: HiTrace_Flag = HiTrace_Flag(16);
    /// Failure trigger flag. This is a reserved flag.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_FLAG_FAULT_TRIGGER: HiTrace_Flag = HiTrace_Flag(32);
    /// Device-to-device trace point flag. It is a subset of **HITRACE_FLAG_TP_INFO** and is used in debugging
    /// scenarios.When the **HITRACE_FLAG_TP_INFO** flag is set, the **HITRACE_FLAG_D2D_TP_INFO** flag does not take
    /// effect.When **HITRACE_FLAG_TP_INFO** is not set and **HITRACE_FLAG_D2D_TP_INFO** is set, the HiLog logs of the
    /// trace point are printed only when the **mode** parameter is set to **HITRACE_CM_DEVICE** upon calling
    /// **OH_HiTrace_Tracepoint()**.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_FLAG_D2D_TP_INFO: HiTrace_Flag = HiTrace_Flag(64);
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl ::core::ops::BitOr<HiTrace_Flag> for HiTrace_Flag {
    type Output = Self;
    #[inline]
    fn bitor(self, other: Self) -> Self {
        HiTrace_Flag(self.0 | other.0)
    }
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl ::core::ops::BitOrAssign for HiTrace_Flag {
    #[inline]
    fn bitor_assign(&mut self, rhs: HiTrace_Flag) {
        self.0 |= rhs.0;
    }
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl ::core::ops::BitAnd<HiTrace_Flag> for HiTrace_Flag {
    type Output = Self;
    #[inline]
    fn bitand(self, other: Self) -> Self {
        HiTrace_Flag(self.0 & other.0)
    }
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl ::core::ops::BitAndAssign for HiTrace_Flag {
    #[inline]
    fn bitand_assign(&mut self, rhs: HiTrace_Flag) {
        self.0 &= rhs.0;
    }
}
#[repr(transparent)]
/// Enumerates the HiTrace flags.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct HiTrace_Flag(pub ::core::ffi::c_uint);
#[repr(u32)]
#[non_exhaustive]
/// Enumerates the trace point types.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum HiTrace_Tracepoint_Type {
    /// CS trace point.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    HITRACE_TP_CS = 0,
    /// CR trace point.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    HITRACE_TP_CR = 1,
    /// SS trace point.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    HITRACE_TP_SS = 2,
    /// SR trace point.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    HITRACE_TP_SR = 3,
    /// General type, which identifies the trace points except **HITRACE_TP_CS**, **HITRACE_TP_CR**,
    /// **HITRACE_TP_SS**, and **HITRACE_TP_SR**.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    HITRACE_TP_GENERAL = 4,
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl HiTrace_Communication_Mode {
    /// Default communication.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_CM_DEFAULT: HiTrace_Communication_Mode = HiTrace_Communication_Mode(0);
    /// Inter-thread communication.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_CM_THREAD: HiTrace_Communication_Mode = HiTrace_Communication_Mode(1);
    /// Inter-process communication (IPC).
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_CM_PROCESS: HiTrace_Communication_Mode = HiTrace_Communication_Mode(2);
    /// Inter-device communication.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub const HITRACE_CM_DEVICE: HiTrace_Communication_Mode = HiTrace_Communication_Mode(3);
}
#[repr(transparent)]
/// Enumerates the trace communication types.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct HiTrace_Communication_Mode(pub ::core::ffi::c_uint);
#[cfg(feature = "api-19")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
impl HiTrace_Output_Level {
    /// Level used only for debugging, which has the lowest priority.
    ///
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub const HITRACE_LEVEL_DEBUG: HiTrace_Output_Level = HiTrace_Output_Level(0);
    /// Level for the log version.
    ///
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub const HITRACE_LEVEL_INFO: HiTrace_Output_Level = HiTrace_Output_Level(1);
    /// Level for the log version, which has a higher priority than **INFO**.
    ///
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub const HITRACE_LEVEL_CRITICAL: HiTrace_Output_Level = HiTrace_Output_Level(2);
    /// Level for the nolog version, which has the highest priority.
    ///
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub const HITRACE_LEVEL_COMMERCIAL: HiTrace_Output_Level = HiTrace_Output_Level(3);
    /// The maximum output level.
    ///
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub const HITRACE_LEVEL_MAX: HiTrace_Output_Level = HiTrace_Output_Level(3);
}
#[repr(transparent)]
/// Enumerates the HiTrace output levels. The trace output level lower than the threshold does not take effect.
/// The log version threshold is **HITRACE_LEVEL_INFO**, and the nolog version threshold is **HITRACE_LEVEL_COMMERCIAL**.
///
///
/// Available since API-level: 19
#[cfg(feature = "api-19")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct HiTrace_Output_Level(pub ::core::ffi::c_uint);
/// Defines a **HiTraceId** instance.
///
/// HiTraceId
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct HiTraceId {
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 16usize]>,
}
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl HiTraceId {
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn valid(&self) -> u64 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get_const::<0usize, 1u8>() as u64) }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_valid(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set_const::<0usize, 1u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn valid_raw(this: *const Self) -> u64 {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 16usize]>>::raw_get_const::<
                0usize,
                1u8,
            >(::core::ptr::addr_of!((*this)._bitfield_1))
                as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_valid_raw(this: *mut Self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 16usize]>>::raw_set_const::<0usize, 1u8>(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                val as u64,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn ver(&self) -> u64 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get_const::<1usize, 3u8>() as u64) }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_ver(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set_const::<1usize, 3u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn ver_raw(this: *const Self) -> u64 {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 16usize]>>::raw_get_const::<
                1usize,
                3u8,
            >(::core::ptr::addr_of!((*this)._bitfield_1))
                as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_ver_raw(this: *mut Self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 16usize]>>::raw_set_const::<1usize, 3u8>(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                val as u64,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn chainId(&self) -> u64 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get_const::<4usize, 60u8>() as u64) }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_chainId(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set_const::<4usize, 60u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn chainId_raw(this: *const Self) -> u64 {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 16usize]>>::raw_get_const::<
                4usize,
                60u8,
            >(::core::ptr::addr_of!((*this)._bitfield_1))
                as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_chainId_raw(this: *mut Self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 16usize]>>::raw_set_const::<4usize, 60u8>(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                val as u64,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn flags(&self) -> u64 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get_const::<64usize, 12u8>() as u64) }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_flags(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set_const::<64usize, 12u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn flags_raw(this: *const Self) -> u64 {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 16usize]>>::raw_get_const::<
                64usize,
                12u8,
            >(::core::ptr::addr_of!((*this)._bitfield_1))
                as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_flags_raw(this: *mut Self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 16usize]>>::raw_set_const::<64usize, 12u8>(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                val as u64,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn spanId(&self) -> u64 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get_const::<76usize, 26u8>() as u64) }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_spanId(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set_const::<76usize, 26u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn spanId_raw(this: *const Self) -> u64 {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 16usize]>>::raw_get_const::<
                76usize,
                26u8,
            >(::core::ptr::addr_of!((*this)._bitfield_1))
                as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_spanId_raw(this: *mut Self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 16usize]>>::raw_set_const::<76usize, 26u8>(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                val as u64,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn parentSpanId(&self) -> u64 {
        unsafe { ::core::mem::transmute(self._bitfield_1.get_const::<102usize, 26u8>() as u64) }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn set_parentSpanId(&mut self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            self._bitfield_1.set_const::<102usize, 26u8>(val as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn parentSpanId_raw(this: *const Self) -> u64 {
        unsafe {
            ::core::mem::transmute(<__BindgenBitfieldUnit<[u8; 16usize]>>::raw_get_const::<
                102usize,
                26u8,
            >(::core::ptr::addr_of!((*this)._bitfield_1))
                as u64)
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub unsafe fn set_parentSpanId_raw(this: *mut Self, val: u64) {
        unsafe {
            let val: u64 = ::core::mem::transmute(val);
            <__BindgenBitfieldUnit<[u8; 16usize]>>::raw_set_const::<102usize, 26u8>(
                ::core::ptr::addr_of_mut!((*this)._bitfield_1),
                val as u64,
            )
        }
    }
    #[inline]
    #[allow(unnecessary_transmutes)]
    pub fn new_bitfield_1(
        valid: u64,
        ver: u64,
        chainId: u64,
        flags: u64,
        spanId: u64,
        parentSpanId: u64,
    ) -> __BindgenBitfieldUnit<[u8; 16usize]> {
        let mut __bindgen_bitfield_unit: __BindgenBitfieldUnit<[u8; 16usize]> = Default::default();
        __bindgen_bitfield_unit.set_const::<0usize, 1u8>({
            let valid: u64 = unsafe { ::core::mem::transmute(valid) };
            valid as u64
        });
        __bindgen_bitfield_unit.set_const::<1usize, 3u8>({
            let ver: u64 = unsafe { ::core::mem::transmute(ver) };
            ver as u64
        });
        __bindgen_bitfield_unit.set_const::<4usize, 60u8>({
            let chainId: u64 = unsafe { ::core::mem::transmute(chainId) };
            chainId as u64
        });
        __bindgen_bitfield_unit.set_const::<64usize, 12u8>({
            let flags: u64 = unsafe { ::core::mem::transmute(flags) };
            flags as u64
        });
        __bindgen_bitfield_unit.set_const::<76usize, 26u8>({
            let spanId: u64 = unsafe { ::core::mem::transmute(spanId) };
            spanId as u64
        });
        __bindgen_bitfield_unit.set_const::<102usize, 26u8>({
            let parentSpanId: u64 = unsafe { ::core::mem::transmute(parentSpanId) };
            parentSpanId as u64
        });
        __bindgen_bitfield_unit
    }
}
/// Defines a callback to listen for whether the trace capture is enabled.
///
/// # Arguments
///
/// * `traceStatus` - Whether the trace capture is enabled for the current application.
/// The value **true** indicates that the trace capture is enabled, and **false** indicates the opposite.
///
/// Available since API-level: 22
#[cfg(feature = "api-22")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-22")))]
pub type OH_HiTrace_TraceEventListener =
    ::core::option::Option<unsafe extern "C" fn(traceStatus: bool)>;
extern "C" {
    /// Starts tracing.
    /// If the current thread's TLS does not contain a valid HiTrace ID, this function generates one, stores it in TLS, and
    /// returns it.
    /// If the current thread's TLS already contains a valid HiTrace ID, this function does not start tracing and returns an
    /// invalid HiTrace ID with all property values being 0.
    ///
    /// # Arguments
    ///
    /// * `name` - Name of the traced service.
    ///
    /// * `flags` - Trace flags. For details, see [`HiTrace_Flag`](crate::HiTrace_Flag).
    ///
    /// # Returns
    ///
    /// * The [`HiTraceId`](crate::HiTraceId) struct.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_BeginChain(
        name: *const ::core::ffi::c_char,
        flags: ::core::ffi::c_int,
    ) -> HiTraceId;
    /// Stops tracing.Stops tracing and sets the HiTrace ID in the TLS of the current thread to invalid.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_EndChain();
    /// Obtains the HiTrace ID in the TLS of the current thread.
    ///
    ///
    /// # Returns
    ///
    /// * The [`HiTraceId`](crate::HiTraceId) struct.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_GetId() -> HiTraceId;
    /// Sets the given HiTrace ID to the TLS of the current thread. If the given HiTrace ID is invalid, no operation
    /// is performed.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to set.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_SetId(id: *const HiTraceId);
    /// Clears the HiTrace ID in the current thread's TLS.
    ///
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_ClearId();
    /// Creates a trace span.
    /// Specifically, create a **HiTraceId**, use the **chainId** and **spanId** in the TLS of the current thread to
    /// initialize the **chainId** and **parentSpanId** of the **HiTraceId**, generate a new **spanId** for the **HiTraceId**
    /// , and return the **HiTraceId**.
    ///
    ///
    /// # Returns
    ///
    /// * The [`HiTraceId`](crate::HiTraceId) struct.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_CreateSpan() -> HiTraceId;
    /// Adds a trace point for the HiTraceMeter logging.
    /// When **type** is set to **HITRACE_TP_CS** and **HITRACE_TP_SR**, the HiTraceMeter tracing starts. When **type** is
    /// set to **HITRACE_TP_CR** and **HITRACE_TP_SS**, the HiTraceMeter tracing ends. When **type** is set to **
    /// HITRACE_TP_GENERAL**, the HiTraceMeter tracing does not start.
    /// The tracing points of **HITRACE_TP_CS** and **HITRACE_TP_CR** must be used in pairs; the tracing points of **
    /// HITRACE_TP_SR** and **HITRACE_TP_SS** must be used in pairs. Otherwise, the start and end trace points of
    /// HiTraceMeter cannot match each other.
    ///
    /// # Arguments
    ///
    /// * `mode` - Trace communication mode. For details, see [`HiTrace_Communication_Mode`](crate::HiTrace_Communication_Mode).
    ///
    /// * `type` - Trace information type. For details, see [`HiTrace_Tracepoint_Type`](crate::HiTrace_Tracepoint_Type).
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) for implementing trace points.
    ///
    /// * `fmt` - Formatted string of the trace description information passed by the HiTraceMeter logging.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_Tracepoint(
        mode: HiTrace_Communication_Mode,
        type_: HiTrace_Tracepoint_Type,
        id: *const HiTraceId,
        fmt: *const ::core::ffi::c_char,
        ...
    );
    /// Initializes a **HiTraceId**.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to initialize.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_InitId(id: *mut HiTraceId);
    /// Creates a **HiTraceId** based on a byte array.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to create.
    ///
    /// * `pIdArray` - Byte array.
    ///
    /// * `len` - Length of the byte array.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_IdFromBytes(id: *mut HiTraceId, pIdArray: *const u8, len: ::core::ffi::c_int);
    /// Checks whether the **HiTraceId** is valid.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to check.
    ///
    /// # Returns
    ///
    /// * The value **true** indicates that [`HiTraceId`](crate::HiTraceId) is valid, and **false** indicates the opposite.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_IsIdValid(id: *const HiTraceId) -> bool;
    /// Checks whether the trace flag is enabled for the **HiTraceId**.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to check.
    ///
    /// * `flag` - Trace flag. For details, see [`HiTrace_Flag`](crate::HiTrace_Flag).
    ///
    /// # Returns
    ///
    /// * The value **true** indicates that the flag is enabled for the [`HiTraceId`](crate::HiTraceId), and **false** indicates the
    /// opposite.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_IsFlagEnabled(id: *const HiTraceId, flag: HiTrace_Flag) -> bool;
    /// Enables the trace flag specified in **HiTraceId**.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) for which the trace flag is enabled.
    ///
    /// * `flag` - Trace flag. For details, see [`HiTrace_Flag`](crate::HiTrace_Flag).
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_EnableFlag(id: *const HiTraceId, flag: HiTrace_Flag);
    /// Obtains the trace flag set in **HiTraceId**.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) for which the trace flag is obtained.
    ///
    /// # Returns
    ///
    /// * Trace flag set in [`HiTraceId`](crate::HiTraceId).
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_GetFlags(id: *const HiTraceId) -> ::core::ffi::c_int;
    /// Sets the trace flag to [`HiTraceId`](crate::HiTraceId).
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to which the trace flag is set.
    ///
    /// * `flags` - Trace flag. For details, see [`HiTrace_Flag`](crate::HiTrace_Flag).
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_SetFlags(id: *mut HiTraceId, flags: ::core::ffi::c_int);
    /// Obtains the trace chain ID in **HiTraceId**.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) for which the trace chain ID is obtained.
    ///
    /// # Returns
    ///
    /// * Trace chain ID.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_GetChainId(id: *const HiTraceId) -> u64;
    /// Sets the trace chain ID in **HiTraceId**.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to which the trace chain ID is to be set.
    ///
    /// * `chainId` - Trace chain ID to set.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_SetChainId(id: *mut HiTraceId, chainId: u64);
    /// Obtains the span ID in **HiTraceId**.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) for which span ID is obtained.
    ///
    /// # Returns
    ///
    /// * Span ID set in [`HiTraceId`](crate::HiTraceId).
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_GetSpanId(id: *const HiTraceId) -> u64;
    /// Sets the span ID in **HiTraceId**.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to which the span ID is set.
    ///
    /// * `spanId` - Span ID to set.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_SetSpanId(id: *mut HiTraceId, spanId: u64);
    /// Obtains the parent span ID in **HiTraceId**.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) for which the parent span ID is obtained.
    ///
    /// # Returns
    ///
    /// * Parent span ID set in [`HiTraceId`](crate::HiTraceId).
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_GetParentSpanId(id: *const HiTraceId) -> u64;
    /// Sets the **ParentSpanId** in a **HiTraceId** instance.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to which the parent span ID is set.
    ///
    /// * `parentSpanId` - Parent span ID to set.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_SetParentSpanId(id: *mut HiTraceId, parentSpanId: u64);
    /// Converts **HiTraceId** into a byte array for cache or communication.
    ///
    /// # Arguments
    ///
    /// * `id` - [`HiTraceId`](crate::HiTraceId) to convert.
    ///
    /// * `pIdArray` - Byte array.
    ///
    /// * `len` - Length of the byte array.
    ///
    /// # Returns
    ///
    /// * Returns the length of the byte array after conversion.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_HiTrace_IdToBytes(
        id: *const HiTraceId,
        pIdArray: *mut u8,
        len: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
    /// Marks the start of a synchronous trace.
    /// This API is used with **OH_HiTrace_FinishTrace()** in pairs.
    /// The two APIs can be nested. The stack data structure is used for matching during trace parsing.
    /// Since API version 19, you are advised to use the **OH_HiTrace_StartTraceEx()** API to specify the trace output level.
    ///
    /// # Arguments
    ///
    /// * `name` - Name of a synchronous trace.
    ///
    /// Available since API-level: 10
    pub fn OH_HiTrace_StartTrace(name: *const ::core::ffi::c_char);
    /// Marks the end of a synchronous trace.
    /// This API must be used with **OH_HiTrace_StartTrace()** in pairs. During trace parsing, the system matches it with
    /// the latest **OH_HiTrace_StartTrace()** API in the service process.
    /// Since API version 19, you are advised to use the **OH_HiTrace_FinishTraceEx()** API to specify the trace output
    /// level.
    ///
    /// Available since API-level: 10
    pub fn OH_HiTrace_FinishTrace();
    /// Marks the start of an asynchronous trace.
    /// This API is used to start tracing before an asynchronous operation. The start and end of an asynchronous trace do
    /// not occur in sequence. Therefore, a unique task ID is required to identify them.
    /// It must be used with **OH_HiTrace_FinishAsyncTrace()** in pairs. The start and end identified by the same name and
    /// task ID constitute an asynchronous trace task.
    /// If multiple trace tasks with the same name need to be performed at the same time or a trace task needs to be
    /// performed multiple times concurrently, different task IDs must be specified.
    /// If the trace tasks with the same name are not performed at the same time, the same **taskId** can be used.
    /// Since API version 19, you are advised to use the **OH_HiTrace_StartAsyncTraceEx()** API to specify the trace output
    /// level and category.
    ///
    /// # Arguments
    ///
    /// * `name` - Name of the asynchronous trace.
    ///
    /// * `taskId` - ID of the asynchronous trace. The start and end of an asynchronous trace do not occur in sequence.
    /// Therefore, the start and end of an asynchronous trace need to be matched based on the task name and the unique task
    /// ID together.
    ///
    /// Available since API-level: 10
    pub fn OH_HiTrace_StartAsyncTrace(name: *const ::core::ffi::c_char, taskId: i32);
    /// Marks the end of an asynchronous trace.
    /// This API is called in the callback function after an asynchronous trace is complete.
    /// It is used with **OH_HiTrace_StartAsyncTrace()** in pairs. Its name and task ID must be the same as those of **
    /// OH_HiTrace_StartAsyncTrace()**.
    /// Since API version 19, you are advised to use the **OH_HiTrace_FinishAsyncTraceEx()** API to specify the trace output
    /// level.
    ///
    /// # Arguments
    ///
    /// * `name` - Name of the asynchronous trace.
    ///
    /// * `taskId` - ID of the asynchronous trace. The start and end of an asynchronous trace do not occur in sequence.
    /// Therefore, the start and end of an asynchronous trace need to be matched based on the task name and the unique task
    /// ID together.
    ///
    /// Available since API-level: 10
    pub fn OH_HiTrace_FinishAsyncTrace(name: *const ::core::ffi::c_char, taskId: i32);
    /// Traces the value change of an integer variable based on its name.
    /// This API can be executed for multiple times to trace the value change of a given integer variable at different time
    /// points.
    /// Since API version 19, you are advised to use the **OH_HiTrace_CountTraceEx()** API to specify the trace output level.
    ///
    /// # Arguments
    ///
    /// * `name` - Name of the integer variable. It does not need to be the same as the real variable name.
    ///
    /// * `count` - Integer value.
    ///
    /// Available since API-level: 10
    pub fn OH_HiTrace_CountTrace(name: *const ::core::ffi::c_char, count: i64);
    /// Marks the start of a synchronous trace task with the trace output level specified.
    /// This API is used with **OH_HiTrace_FinishTraceEx()** in pairs.
    /// The two APIs can be nested. The stack data structure is used for matching during trace parsing.
    ///
    /// # Arguments
    ///
    /// * `level` - Trace output level.
    ///
    /// * `name` - Name of a synchronous trace.
    ///
    /// * `customArgs` - Key-value pair. Use commas (,) to separate multiple key-value pairs, for example, **"key1=value1,
    /// key2=value2"**.
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub fn OH_HiTrace_StartTraceEx(
        level: HiTrace_Output_Level,
        name: *const ::core::ffi::c_char,
        customArgs: *const ::core::ffi::c_char,
    );
    /// Marks the end of a synchronous trace task with the trace output level specified.
    /// It must be used with **OH_HiTrace_StartTraceEx()** in pairs. Its level must be the same as those of **
    /// OH_HiTrace_StartTraceEx()**.
    /// During trace data parsing, the system matches it with the **OH_HiTrace_StartTraceEx()** API recently invoked in the
    /// service process.
    /// # Arguments
    ///
    /// * `level` - Trace output level.
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub fn OH_HiTrace_FinishTraceEx(level: HiTrace_Output_Level);
    /// Marks the start of an asynchronous trace task with the trace output level specified.
    /// This API is used to start tracing before an asynchronous operation. The start and end of an asynchronous trace do
    /// not occur in sequence. Therefore, a unique task ID is required to identify them.
    /// It is used with **OH_HiTrace_FinishAsyncTraceEx()** in pairs. The start and end identified by the same name and task
    /// ID constitute an asynchronous trace task.
    /// If multiple trace tasks with the same name need to be performed at the same time or a trace task needs to be
    /// performed multiple times concurrently, different task IDs must be specified.
    /// If the trace tasks with the same name are not performed at the same time, the same **taskId** can be used.
    /// Task IDs of different processes does not interfere with each other.
    ///
    /// # Arguments
    ///
    /// * `level` - Trace output level.
    ///
    /// * `name` - Name of the asynchronous trace.
    ///
    /// * `taskId` - ID of the asynchronous trace.
    ///
    /// * `customCategory` - Custom category name, which is used to collect asynchronous trace data of the same type.
    ///
    /// * `customArgs` - Key-value pair. Use commas (,) to separate multiple key-value pairs, for example, **"key1=value1,
    /// key2=value2"**.
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub fn OH_HiTrace_StartAsyncTraceEx(
        level: HiTrace_Output_Level,
        name: *const ::core::ffi::c_char,
        taskId: i32,
        customCategory: *const ::core::ffi::c_char,
        customArgs: *const ::core::ffi::c_char,
    );
    /// Marks the end of an asynchronous trace task with the trace output level specified.
    /// This API is used to stop tracing after an asynchronous operation is complete, for example, in a callback function.
    /// It is used with **OH_HiTrace_StartAsyncTraceEx()** in pairs. Its level, name and task ID must be the same as those
    /// of **OH_HiTrace_StartAsyncTraceEx()**.
    ///
    /// # Arguments
    ///
    /// * `level` - Trace output level.
    ///
    /// * `name` - Name of the asynchronous trace.
    ///
    /// * `taskId` - ID of the asynchronous trace.
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub fn OH_HiTrace_FinishAsyncTraceEx(
        level: HiTrace_Output_Level,
        name: *const ::core::ffi::c_char,
        taskId: i32,
    );
    /// Marks an integer variable trace task with the trace output level specified.
    ///
    /// # Arguments
    ///
    /// * `level` - Trace output level.
    ///
    /// * `name` - Name of the integer variable. It does not need to be the same as the actual variable name.
    ///
    /// * `count` - Integer value.
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub fn OH_HiTrace_CountTraceEx(
        level: HiTrace_Output_Level,
        name: *const ::core::ffi::c_char,
        count: i64,
    );
    /// Checks whether trace capture is enabled for an application.
    ///
    ///
    /// # Returns
    ///
    /// * When it is enabled, **true** is returned;
    /// when it is disabled or stopped, **false** is returned. In this case,
    /// calling the HiTraceMeter API does not take effect.
    ///
    /// Available since API-level: 19
    #[cfg(feature = "api-19")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-19")))]
    pub fn OH_HiTrace_IsTraceEnabled() -> bool;
    /// Registers a callback to notify whether the application trace capture is enabled. This API uses a synchronous
    /// callback to return the result.
    ///
    /// # Arguments
    ///
    /// * `callback` - Registered callback.
    ///
    /// # Returns
    ///
    /// * Callback registration status.
    /// >= **0**: The registration is successful. The callback index for unregistration is returned. The index ranges from 0
    /// to 9.
    /// **-1**: The maximum number of callbacks has been reached.
    /// **-2**: Invalid parameter. The parameter is not of the **TraceEventListener** type.
    ///
    /// Available since API-level: 22
    #[cfg(feature = "api-22")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-22")))]
    pub fn OH_HiTrace_RegisterTraceListener(callback: OH_HiTrace_TraceEventListener) -> i32;
    /// Unregisters the callback used to notify whether the application trace capture is enabled.
    /// You can use this function to unregister the callback function associated with the callback index returned by
    /// [`OH_HiTrace_RegisterTraceListener`](crate::OH_HiTrace_RegisterTraceListener).
    ///
    /// # Arguments
    ///
    /// * `index` - Index of the registered callback.
    ///
    /// # Returns
    ///
    /// * Callback unregistration status.
    /// **0**: Unregistration succeeded.
    /// **-1**: The callback corresponding to the index is not registered.
    /// **-2**: Invalid index. The index value is not within the range of 0 to 9.
    ///
    /// Available since API-level: 22
    #[cfg(feature = "api-22")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-22")))]
    pub fn OH_HiTrace_UnregisterTraceListener(index: i32) -> i32;
}
