// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::cparcel::{OHIPCRemoteStub, OH_IPC_MemAllocator};
use ohos_sys_opaque_types::{OHIPCParcel, OHIPCRemoteProxy};

/// Defines an object that receives death notifications.
///
///
/// Required System Capabilities: SystemCapability.Communication.IPC.Core
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[repr(C)]
pub struct OHIPCDeathRecipient {
    _unused: [u8; 0],
}
/// Called to process the peer request at the stub.
///
///
/// Required System Capabilities: SystemCapability.Communication.IPC.Core
/// # Arguments
///
/// * `code` - Customized communication command word.
/// Value range: \[0x01, 0x00ffffff\]
///
/// * `data` - Pointer to the requested data object. It cannot be NULL or released in the function.
///
/// * `reply` - Pointer to the response data object. It cannot be NULL or released in the function. If this function
/// returns an error, data cannot be written to this parameter.
///
/// * `userData` - Pointer to the private user data. It can be NULL.
///
/// # Returns
///
/// * Returns [`OH_IPC_ErrorCode#OH_IPC_SUCCESS`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_SUCCESS) if the operation is successful.
/// Returns a custom error code in the range \[1909001, 1909999\] or a system error code otherwise.
/// If the custom error code is out of range, [`OH_IPC_ErrorCode#OH_IPC_INVALID_USER_ERROR_CODE`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_INVALID_USER_ERROR_CODE) is returned.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_OnRemoteRequestCallback = ::core::option::Option<
    unsafe extern "C" fn(
        code: u32,
        data: *const OHIPCParcel,
        reply: *mut OHIPCParcel,
        userData: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int,
>;
/// Called when an observed object is destroyed.
///
///
/// Required System Capabilities: SystemCapability.Communication.IPC.Core
/// # Arguments
///
/// * `userData` - Pointer to the private user data. It can be NULL.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_OnRemoteDestroyCallback =
    ::core::option::Option<unsafe extern "C" fn(userData: *mut ::core::ffi::c_void)>;
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
impl OH_IPC_RequestMode {
    /// Synchronous request.
    pub const OH_IPC_REQUEST_MODE_SYNC: OH_IPC_RequestMode = OH_IPC_RequestMode(0);
    /// Asynchronous request.
    pub const OH_IPC_REQUEST_MODE_ASYNC: OH_IPC_RequestMode = OH_IPC_RequestMode(1);
}
#[repr(transparent)]
/// Enumerates the IPC request modes.
///
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_IPC_RequestMode(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct OH_IPC_MessageOption {
    /// Message request mode.
    pub mode: OH_IPC_RequestMode,
    /// Parameter reserved for RPC, which is invalid for IPC.
    pub timeout: u32,
    /// Reserved parameter, which must be NULL.
    pub reserved: *mut ::core::ffi::c_void,
}
/// Defines a callback to be invoked when the remote **OHIPCRemoteStub** object dies unexpectedly.
///
///
/// Required System Capabilities: SystemCapability.Communication.IPC.Core
/// # Arguments
///
/// * `userData` - Pointer to the private user data. It can be NULL.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_OnDeathRecipientCallback =
    ::core::option::Option<unsafe extern "C" fn(userData: *mut ::core::ffi::c_void)>;
/// Defines a callback to be invoked when the **OHIPCDeathRecipient** object is destroyed.
///
///
/// Required System Capabilities: SystemCapability.Communication.IPC.Core
/// # Arguments
///
/// * `userData` - Pointer to the private user data. It can be NULL.
///
/// Available since API-level: 12
#[cfg(feature = "api-12")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
pub type OH_OnDeathRecipientDestroyCallback =
    ::core::option::Option<unsafe extern "C" fn(userData: *mut ::core::ffi::c_void)>;
extern "C" {
    /// Creates an **OHIPCRemoteStub** object.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `descriptor` - Pointer to the descriptor of the **OHIPCRemoteStub** object to create. It cannot be NULL.
    ///
    /// * `requestCallback` - Callback used to process the data request. It cannot be NULL.
    ///
    /// * `destroyCallback` - Callback to be invoked when the object is destroyed. It can be NULL.
    ///
    /// * `userData` - Pointer to the private user data. It can be NULL.
    ///
    /// # Returns
    ///
    /// * Returns the pointer to the **OHIPCRemoteStub** object created if the operation is successful; returns NULL
    /// otherwise.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCRemoteStub_Create(
        descriptor: *const ::core::ffi::c_char,
        requestCallback: OH_OnRemoteRequestCallback,
        destroyCallback: OH_OnRemoteDestroyCallback,
        userData: *mut ::core::ffi::c_void,
    ) -> *mut OHIPCRemoteStub;
    /// Destroys an **OHIPCRemoteStub** object.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `stub` - Pointer to the **OHIPCRemoteStub** object to destroy.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCRemoteStub_Destroy(stub: *mut OHIPCRemoteStub);
    /// Destroys an **OHIPCRemoteProxy** object.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `proxy` - Pointer to the **OHIPCRemoteProxy** object to destroy.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCRemoteProxy_Destroy(proxy: *mut OHIPCRemoteProxy);
    /// Sends an IPC message.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `proxy` - Pointer to the **OHIPCRemoteProxy** object. It cannot be NULL.
    ///
    /// * `code` - Customized IPC command word, in the range \[0x01, 0x00ffffff\].
    ///
    /// * `data` - Pointer to the requested data object. It cannot be NULL.
    ///
    /// * `reply` - Pointer to the response data object. It cannot be NULL in the case of a synchronous request, and can be
    /// NULL in the case of an asynchronous request.
    ///
    /// * `option` - Pointer to the message option. It can be NULL, which indicates a synchronous request.
    ///
    /// # Returns
    ///
    /// * Returns [`OH_IPC_ErrorCode#OH_IPC_SUCCESS`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_SUCCESS) if the message is sent successfully.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_CHECK_PARAM_ERROR`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_CHECK_PARAM_ERROR) if invalid parameters are found.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_DEAD_REMOTE_OBJECT`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_DEAD_REMOTE_OBJECT) if the remote **OHIPCRemoteStub** object dies.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_CODE_OUT_OF_RANGE`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_CODE_OUT_OF_RANGE) if the code is out of range.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_INNER_ERROR`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_INNER_ERROR) or a custom error code in other cases.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCRemoteProxy_SendRequest(
        proxy: *const OHIPCRemoteProxy,
        code: u32,
        data: *const OHIPCParcel,
        reply: *mut OHIPCParcel,
        option: *const OH_IPC_MessageOption,
    ) -> ::core::ffi::c_int;
    /// Obtains the interface descriptor from the stub.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `proxy` - Pointer to the **OHIPCRemoteProxy** object. It cannot be NULL.
    ///
    /// * `descriptor` - Pointer to the address of the memory for holding the interface descriptor. The memory is allocated
    /// by the allocator provided by the user and needs to be released. This pointer cannot be NULL. If an error code is
    /// returned, you still need to check whether the memory is empty and release the memory. Otherwise, memory leaks may
    /// occur.
    ///
    /// * `len` - Pointer to the length of the data written to the descriptor, including the terminator. It cannot be NULL.
    ///
    /// * `allocator` - Memory allocator specified by the user for allocating memory for **identity**. It cannot be NULL.
    ///
    /// # Returns
    ///
    /// * Returns [`OH_IPC_ErrorCode#OH_IPC_SUCCESS`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_SUCCESS) if the message is sent successfully.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_CHECK_PARAM_ERROR`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_CHECK_PARAM_ERROR) if the parameters are incorrect.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_DEAD_REMOTE_OBJECT`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_DEAD_REMOTE_OBJECT) if the remote **OHIPCRemoteStub** object dies.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_MEM_ALLOCATOR_ERROR`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_MEM_ALLOCATOR_ERROR) if the memory allocation fails.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_PARCEL_READ_ERROR`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_PARCEL_READ_ERROR) or a custom error code if the data in the serialized
    /// object fails to be read.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCRemoteProxy_GetInterfaceDescriptor(
        proxy: *mut OHIPCRemoteProxy,
        descriptor: *mut *mut ::core::ffi::c_char,
        len: *mut i32,
        allocator: OH_IPC_MemAllocator,
    ) -> ::core::ffi::c_int;
    /// Creates an **OHIPCDeathRecipient** object, which triggers a notification when the **OHIPCRemoteStub** object
    /// dies unexpectedly.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `deathRecipientCallback` - Callback to be invoked when the **OHIPCRemoteStub** object is dead. It cannot be NULL.
    ///
    /// * `destroyCallback` - Callback to be invoked when the object is destroyed. It can be NULL.
    ///
    /// * `userData` - Pointer to the private user data. It can be NULL.
    ///
    /// # Returns
    ///
    /// * Returns the pointer to the **OHIPCDeathRecipient** object created if the operation is successful; returns
    /// NULL otherwise.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCDeathRecipient_Create(
        deathRecipientCallback: OH_OnDeathRecipientCallback,
        destroyCallback: OH_OnDeathRecipientDestroyCallback,
        userData: *mut ::core::ffi::c_void,
    ) -> *mut OHIPCDeathRecipient;
    /// Destroys an **OHIPCDeathRecipient** object.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `recipient` - Pointer to the **OHIPCDeathRecipient** object to destroy.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCDeathRecipient_Destroy(recipient: *mut OHIPCDeathRecipient);
    /// Subscribes to the death of an **OHIPCRemoteStub** object for an **OHIPCRemoteProxy** object.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `proxy` - Pointer to the **OHIPCRemoteProxy** object that subscribes to the death notification. It cannot be NULL.
    ///
    /// * `recipient` - Pointer to the object that receives the death notification of the **OHIPCRemoteStub** object. It
    /// cannot be NULL.
    ///
    /// # Returns
    ///
    /// * Returns [`OH_IPC_ErrorCode#OH_IPC_SUCCESS`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_SUCCESS) if the operation is successful.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_CHECK_PARAM_ERROR`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_CHECK_PARAM_ERROR) if the parameters are incorrect.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_INNER_ERROR`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_INNER_ERROR) in other cases.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCRemoteProxy_AddDeathRecipient(
        proxy: *mut OHIPCRemoteProxy,
        recipient: *mut OHIPCDeathRecipient,
    ) -> ::core::ffi::c_int;
    /// Unsubscribes from the death of the **OHIPCRemoteStub** object for an **OHIPCRemoteProxy** object.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `proxy` - Pointer to the **OHIPCRemoteProxy** object that unsubscribes from the death notification. It cannot be
    /// NULL.
    ///
    /// * `recipient` - Pointer to the object that receives the death notification of the **OHIPCRemoteStub** object. It
    /// cannot be NULL.
    ///
    /// # Returns
    ///
    /// * Returns [`OH_IPC_ErrorCode#OH_IPC_SUCCESS`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_SUCCESS) if the operation is successful.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_CHECK_PARAM_ERROR`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_CHECK_PARAM_ERROR) if the parameters are incorrect.
    /// Returns [`OH_IPC_ErrorCode#OH_IPC_INNER_ERROR`](crate::error_code::OH_IPC_ErrorCode::OH_IPC_INNER_ERROR) in other cases.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCRemoteProxy_RemoveDeathRecipient(
        proxy: *mut OHIPCRemoteProxy,
        recipient: *mut OHIPCDeathRecipient,
    ) -> ::core::ffi::c_int;
    /// Checks whether the **OHIPCRemoteStub** object corresponding to the **OHIPCRemoteProxy** object is dead.
    ///
    ///
    /// Required System Capabilities: SystemCapability.Communication.IPC.Core
    /// # Arguments
    ///
    /// * `proxy` - Pointer to the **OHIPCRemoteProxy** object to check. It cannot be NULL.
    ///
    /// # Returns
    ///
    /// * Returns **1** if the **OHIPCRemoteStub** object is dead or invalid parameters are found; returns **0**
    /// otherwise. If invalid parameters are found, the **OHIPCRemoteStub** object does not exist.
    ///
    /// Available since API-level: 12
    #[cfg(feature = "api-12")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-12")))]
    pub fn OH_IPCRemoteProxy_IsRemoteDead(proxy: *const OHIPCRemoteProxy) -> ::core::ffi::c_int;
}
