// automatically generated by rust-bindgen 0.73.2

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::runtime::{
    AbilityRuntimeResult, AbilityRuntime_StartVisibility, AbilityRuntime_SupportedWindowMode,
    AbilityRuntime_WindowMode,
};
use ohos_sys_opaque_types::OH_PixelmapNative;

#[repr(C)]
#[derive(Debug)]
pub struct AbilityRuntime_StartOptions {
    _unused: [u8; 0],
}
extern "C" {
    /// Create start options.
    ///
    ///
    /// # Returns
    ///
    /// * Returns the newly created AbilityRuntime_StartOptions object.
    ///
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_CreateStartOptions() -> *mut AbilityRuntime_StartOptions;
    /// Destroy input start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to be deleted.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_DestroyStartOptions(
        startOptions: *mut *mut AbilityRuntime_StartOptions,
    ) -> AbilityRuntimeResult;
    /// Set window mode for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set window mode for.
    ///
    /// * `windowMode` - The window mode.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions or windowMode is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsWindowMode(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowMode: AbilityRuntime_WindowMode,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsWindowMode(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowMode: *mut AbilityRuntime_WindowMode,
    ) -> AbilityRuntimeResult;
    /// Set display id for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set display id for.
    ///
    /// * `displayId` - The display id.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsDisplayId(
        startOptions: *mut AbilityRuntime_StartOptions,
        displayId: i32,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsDisplayId(
        startOptions: *mut AbilityRuntime_StartOptions,
        displayId: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Set with animation flag for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set with animation for.
    ///
    /// * `withAnimation` - The with animation.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsWithAnimation(
        startOptions: *mut AbilityRuntime_StartOptions,
        withAnimation: bool,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsWithAnimation(
        startOptions: *mut AbilityRuntime_StartOptions,
        withAnimation: *mut bool,
    ) -> AbilityRuntimeResult;
    /// Set window left for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set window left for.
    ///
    /// * `windowLeft` - The window left.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsWindowLeft(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowLeft: i32,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsWindowLeft(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowLeft: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Set window top for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set window top for.
    ///
    /// * `windowTop` - The window top.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsWindowTop(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowTop: i32,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsWindowTop(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowTop: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Set window height for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set window height for.
    ///
    /// * `windowHeight` - The window height.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsWindowHeight(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowHeight: i32,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsWindowHeight(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowHeight: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Set window width for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set window width for.
    ///
    /// * `windowWidth` - The window width.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsWindowWidth(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowWidth: i32,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsWindowWidth(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowWidth: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Set start visibility for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set start visibility for.
    ///
    /// * `startVisibility` - The start visibility.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsStartVisibility(
        startOptions: *mut AbilityRuntime_StartOptions,
        startVisibility: AbilityRuntime_StartVisibility,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsStartVisibility(
        startOptions: *mut AbilityRuntime_StartOptions,
        startVisibility: *mut AbilityRuntime_StartVisibility,
    ) -> AbilityRuntimeResult;
    /// Set start window icon for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set start window icon for.
    ///
    /// * `startWindowIcon` - The start window icon.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid
    /// or startWindowIcon is nullptr.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsStartWindowIcon(
        startOptions: *mut AbilityRuntime_StartOptions,
        startWindowIcon: *mut OH_PixelmapNative,
    ) -> AbilityRuntimeResult;
    /// Get start window icon from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to get start window icon from.
    ///
    /// * `startWindowIcon` - The obtained start window icon.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid
    /// or startWindowIcon is NOT nullptr.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_GetStartOptionsStartWindowIcon(
        startOptions: *mut AbilityRuntime_StartOptions,
        startWindowIcon: *mut *mut OH_PixelmapNative,
    ) -> AbilityRuntimeResult;
    /// Set start window background color for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set start window background color for.
    ///
    /// * `startWindowBackgroundColor` - The start window background color.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid
    /// or startWindowBackgroundColor is nullptr.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsStartWindowBackgroundColor(
        startOptions: *mut AbilityRuntime_StartOptions,
        startWindowBackgroundColor: *const ::core::ffi::c_char,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsStartWindowBackgroundColor(
        startOptions: *mut AbilityRuntime_StartOptions,
        startWindowBackgroundColor: *mut *mut ::core::ffi::c_char,
        size: *mut usize,
    ) -> AbilityRuntimeResult;
    /// Set start window modes for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set start window modes for.
    ///
    /// * `supportedWindowModes` - The start window modes.
    ///
    /// * `size` - The size of start window modes.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions or supportWindowMode
    /// or size is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsSupportedWindowModes(
        startOptions: *mut AbilityRuntime_StartOptions,
        supportedWindowModes: *mut AbilityRuntime_SupportedWindowMode,
        size: usize,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsSupportedWindowModes(
        startOptions: *mut AbilityRuntime_StartOptions,
        supportedWindowModes: *mut *mut AbilityRuntime_SupportedWindowMode,
        size: *mut usize,
    ) -> AbilityRuntimeResult;
    /// Set min window width for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set min window width for.
    ///
    /// * `minWindowWidth` - The min window width.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsMinWindowWidth(
        startOptions: *mut AbilityRuntime_StartOptions,
        minWindowWidth: i32,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsMinWindowWidth(
        startOptions: *mut AbilityRuntime_StartOptions,
        minWindowWidth: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Set max window width for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set max window width for.
    ///
    /// * `maxWindowWidth` - The max window width.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsMaxWindowWidth(
        startOptions: *mut AbilityRuntime_StartOptions,
        maxWindowWidth: i32,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsMaxWindowWidth(
        startOptions: *mut AbilityRuntime_StartOptions,
        maxWindowWidth: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Set min window height for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set min window height for.
    ///
    /// * `minWindowHeight` - The min window height.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsMinWindowHeight(
        startOptions: *mut AbilityRuntime_StartOptions,
        minWindowHeight: i32,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsMinWindowHeight(
        startOptions: *mut AbilityRuntime_StartOptions,
        minWindowHeight: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Set max window height for start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - The options to set max window height for.
    ///
    /// * `maxWindowHeight` - The max window height.
    ///
    /// # Returns
    ///
    /// * The error code.
    /// [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if the startOptions is invalid.
    ///
    /// Available since API-level: 17
    #[cfg(feature = "api-17")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-17")))]
    pub fn OH_AbilityRuntime_SetStartOptionsMaxWindowHeight(
        startOptions: *mut AbilityRuntime_StartOptions,
        maxWindowHeight: i32,
    ) -> AbilityRuntimeResult;
    pub fn OH_AbilityRuntime_GetStartOptionsMaxWindowHeight(
        startOptions: *mut AbilityRuntime_StartOptions,
        maxWindowHeight: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get the window mode from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `windowMode` - \[out\] The obtained window mode. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsWindowModeValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowMode: *mut AbilityRuntime_WindowMode,
    ) -> AbilityRuntimeResult;
    /// Get the display ID from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `displayId` - \[out\] The obtained display ID. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsDisplayIdValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        displayId: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get whether animation is enabled from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `withAnimation` - \[out\] The obtained animation flag. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsWithAnimationValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        withAnimation: *mut bool,
    ) -> AbilityRuntimeResult;
    /// Get the window left position from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `windowLeft` - \[out\] The obtained window left position. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsWindowLeftValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowLeft: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get the window top position from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `windowTop` - \[out\] The obtained window top position. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsWindowTopValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowTop: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get the window height from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `windowHeight` - \[out\] The obtained window height. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsWindowHeightValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowHeight: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get the window width from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `windowWidth` - \[out\] The obtained window width. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsWindowWidthValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        windowWidth: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get the start visibility from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `startVisibility` - \[out\] The obtained start visibility. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsStartVisibilityValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        startVisibility: *mut AbilityRuntime_StartVisibility,
    ) -> AbilityRuntimeResult;
    /// Get the start window background color from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `startWindowBackgroundColor` - \[out\] The pointer used to receive the UTF-8 background color string.
    /// It must not be NULL and must point to NULL before the call.
    ///
    /// * `size` - \[out\] The length of the background color string, excluding the trailing NUL.
    /// It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_INTERNAL`](crate::runtime::AbilityRuntimeErrorCode::INTERNAL) if error occurred in malloc.
    ///
    /// **Note:** If the background color is not set, [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) is returned,
    /// *startWindowBackgroundColor remains NULL, and *size is set to 0.
    ///
    /// **Note:** Release `startWindowBackgroundColor` with `free`.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsStartWindowBackgroundColorValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        startWindowBackgroundColor: *mut *mut ::core::ffi::c_char,
        size: *mut usize,
    ) -> AbilityRuntimeResult;
    /// Get the supported start window modes from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `supportedWindowModes` - \[out\] The pointer used to receive the supported start window modes.
    /// It must not be NULL and must point to NULL before the call.
    ///
    /// * `size` - \[out\] The number of returned supported start window modes. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_INTERNAL`](crate::runtime::AbilityRuntimeErrorCode::INTERNAL) if error occurred in malloc.
    ///
    /// **Note:** If no supported window modes are set, [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) is returned,
    /// *supportedWindowModes remains NULL, and *size is set to 0.
    ///
    /// **Note:** Release `supportedWindowModes` with `free`.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsSupportedWindowModesValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        supportedWindowModes: *mut *mut AbilityRuntime_SupportedWindowMode,
        size: *mut usize,
    ) -> AbilityRuntimeResult;
    /// Get the minimum window width from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `minWindowWidth` - \[out\] The obtained minimum window width. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsMinWindowWidthValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        minWindowWidth: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get the maximum window width from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `maxWindowWidth` - \[out\] The obtained maximum window width. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsMaxWindowWidthValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        maxWindowWidth: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get the minimum window height from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `minWindowHeight` - \[out\] The obtained minimum window height. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsMinWindowHeightValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        minWindowHeight: *mut i32,
    ) -> AbilityRuntimeResult;
    /// Get the maximum window height from start options.
    ///
    /// # Arguments
    ///
    /// * `startOptions` - \[in\] The start options to read.
    ///
    /// * `maxWindowHeight` - \[out\] The obtained maximum window height. It must not be NULL.
    ///
    /// # Returns
    ///
    /// - [`ABILITY_RUNTIME_ERROR_CODE_NO_ERROR`](crate::runtime::AbilityRuntimeResult) if the operation is successful.
    /// - [`ABILITY_RUNTIME_ERROR_CODE_PARAM_INVALID`](crate::runtime::AbilityRuntimeErrorCode::PARAM_INVALID) if any parameter is invalid.
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AbilityRuntime_GetStartOptionsMaxWindowHeightValue(
        startOptions: *mut AbilityRuntime_StartOptions,
        maxWindowHeight: *mut i32,
    ) -> AbilityRuntimeResult;
}
