// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(deprecated)]
use crate::avcodec_base::OH_AVDataSource;
#[allow(unused_imports)]
use crate::averrors::OH_AVErrCode;

/// Defines a struct for the HTTP header.
///
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
pub struct OH_AVHttpHeader {
    _unused: [u8; 0],
}
/// Defines a struct for the media source.
///
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
pub struct OH_AVMediaSource {
    _unused: [u8; 0],
}
/// Defines a load request object for the media resource, through which the application obtains the location of
/// the requested resource.
///
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
pub struct OH_AVMediaSourceLoadingRequest {
    _unused: [u8; 0],
}
/// Declares the media source loader type, which is implemented by the application.
///
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[repr(C)]
pub struct OH_AVMediaSourceLoader {
    _unused: [u8; 0],
}
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
impl AVLoadingRequestError {
    /// The resource is successfully downloaded.
    pub const AV_LOADING_ERROR_SUCCESS: AVLoadingRequestError = AVLoadingRequestError(0);
    /// The resource is not ready and cannot be accessed.
    pub const AV_LOADING_ERROR_NOT_READY: AVLoadingRequestError = AVLoadingRequestError(1);
    /// The resource URL does not exist.
    pub const AV_LOADING_ERROR_NO_RESOURCE: AVLoadingRequestError = AVLoadingRequestError(2);
    /// The UUID of the resource handle is invalid.
    pub const AV_LOADING_ERROR_INVALID_HANDLE: AVLoadingRequestError = AVLoadingRequestError(3);
    /// The client does not have the permission to request the resource.
    pub const AV_LOADING_ERROR_ACCESS_DENIED: AVLoadingRequestError = AVLoadingRequestError(4);
    /// The access times out.
    pub const AV_LOADING_ERROR_ACCESS_TIMEOUT: AVLoadingRequestError = AVLoadingRequestError(5);
    /// The authorization failed.
    pub const AV_LOADING_ERROR_AUTHORIZE_FAILED: AVLoadingRequestError = AVLoadingRequestError(6);
}
#[repr(transparent)]
/// Enumerates the error codes of network loading requests.
///
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct AVLoadingRequestError(pub ::core::ffi::c_uint);
/// Defines the SourceOpenCallback function which is called by the service.
/// client should process the incoming request
/// and return the unique handle to the open resource.
/// The client must return the handle immediately after processing the request.
/// # Arguments
///
/// * `request` - Parameters for the resource open request,
/// including detailed information about the requested resource and the data push method.
///
/// * `userData` - The data set by user in OH_AVMediaSourceLoader_SetSourceOpenCallback
///
/// # Returns
///
/// * The handler of current resource open request, the handler for the request object is unique.
/// A value greater than 0 means the request is successful.
/// A value less than or equal to 0 means it fails.
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVMediaSourceLoaderOnSourceOpenedCallback = ::core::option::Option<
    unsafe extern "C" fn(
        request: *mut OH_AVMediaSourceLoadingRequest,
        userData: *mut ::core::ffi::c_void,
    ) -> i64,
>;
/// Defines the **SourceReadCallback** function called by the server. The client should record the read request
/// and push data using the [`OH_AVMediaSourceLoadingRequest_RespondData`](crate::avmedia_source::OH_AVMediaSourceLoadingRequest_RespondData) and [`OH_AVMediaSourceLoadingRequest_RespondHeader`](crate::avmedia_source::OH_AVMediaSourceLoadingRequest_RespondHeader)
/// methods of the request object when there is sufficient data. The client must return immediately after the request
/// is processed.
///
/// # Arguments
///
/// * `uuid` - ID of the resource handle.
///
/// * `requestedOffset` - Offset of the current media data relative to the start of the resource.
///
/// * `requestedLength` - Length of the requested data. The value **-1** indicates that the end of the resource has
/// been reached. In this case, call the [`OH_AVMediaSourceLoadingRequest_FinishLoading`](crate::avmedia_source::OH_AVMediaSourceLoadingRequest_FinishLoading) method to notify the
/// player that the push is complete.
///
/// * `userData` - The data set by user in OH_AVMediaSourceLoader_SetSourceReadCallback
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVMediaSourceLoaderOnSourceReadCallback = ::core::option::Option<
    unsafe extern "C" fn(
        uuid: i64,
        requestedOffset: i64,
        requestedLength: i64,
        userData: *mut ::core::ffi::c_void,
    ),
>;
/// Defines the **SourceCloseCallback** function called by the server. The client should release related
/// resources and return immediately after the request is processed.
///
/// # Arguments
///
/// * `uuid` - ID of the resource handle.
///
/// * `userData` - The data set by user in OH_AVMediaSourceLoader_SetSourceCloseCallback
///
/// Available since API-level: 23
#[cfg(feature = "api-23")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
pub type OH_AVMediaSourceLoaderOnSourceClosedCallback =
    ::core::option::Option<unsafe extern "C" fn(uuid: i64, userData: *mut ::core::ffi::c_void)>;
extern "C" {
    /// Creates an HTTP header instance.
    ///
    ///
    /// # Returns
    ///
    /// * Pointer to the **OH_AVHttpHeader** instance if the operation is successful; null pointer if the operation
    /// fails.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVHttpHeader_Create() -> *mut OH_AVHttpHeader;
    /// Releases an HTTP header instance.
    ///
    /// # Arguments
    ///
    /// * `header` - Pointer to the **OH_AVHttpHeader** instance.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The header is a null pointer or the instance fails to be destroyed.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVHttpHeader_Destroy(header: *mut OH_AVHttpHeader) -> OH_AVErrCode;
    /// Obtains the number of records in an HTTP header instance.
    ///
    /// # Arguments
    ///
    /// * `header` - Pointer to the **OH_AVHttpHeader** instance.
    ///
    /// * `count` - Pointer to the number of records in the header instance.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The header is a null pointer.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVHttpHeader_GetCount(header: *mut OH_AVHttpHeader, count: *mut u32) -> OH_AVErrCode;
    /// Adds a key-value pair record to an HTTP header instance.
    ///
    /// # Arguments
    ///
    /// * `header` - Pointer to the **OH_AVHttpHeader** instance.
    ///
    /// * `key` - Pointer to the key name of the record.
    ///
    /// * `value` - Pointer to the value of the record.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): Any parameter is a null pointer.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVHttpHeader_AddRecord(
        header: *mut OH_AVHttpHeader,
        key: *const ::core::ffi::c_char,
        value: *const ::core::ffi::c_char,
    ) -> OH_AVErrCode;
    /// Obtains a key-value pair record in an HTTP header instance by index.
    ///
    /// # Arguments
    ///
    /// * `header` - Pointer to the **OH_AVHttpHeader** instance.
    ///
    /// * `index` - Position of the record in the header.
    ///
    /// * `key` - Double pointer to the key name of the record.
    ///
    /// * `value` - Double pointer to the value of the record.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The header is a null pointer or the index is out of range.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVHttpHeader_GetRecord(
        header: *mut OH_AVHttpHeader,
        index: u32,
        key: *mut *const ::core::ffi::c_char,
        value: *mut *const ::core::ffi::c_char,
    ) -> OH_AVErrCode;
    /// Creates a media source using a URL.
    ///
    /// # Arguments
    ///
    /// * `url` - Pointer to the URL of the media source. The following streaming media formats are supported: HLS, HTTP-
    /// FLV, DASH, and HTTPS.
    ///
    /// * `header` - Pointer to the HTTP header attached to the network request.
    ///
    /// # Returns
    ///
    /// * Pointer to the **OH_AVMediaSource** instance if the operation is successful; null pointer if the operation
    /// fails.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSource_CreateWithUrl(
        url: *const ::core::ffi::c_char,
        header: *mut OH_AVHttpHeader,
    ) -> *mut OH_AVMediaSource;
    /// Creates a media source using **OH_AVDataSource**.
    ///
    /// # Arguments
    ///
    /// * `dataSource` - Pointer to **OH_AVDataSource**.
    ///
    /// # Returns
    ///
    /// * Pointer to the **OH_AVMediaSource** instance if the operation is successful; null pointer if the operation
    /// fails.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSource_CreateWithDataSource(
        dataSource: *mut OH_AVDataSource,
    ) -> *mut OH_AVMediaSource;
    /// Creates a media source using a file descriptor.
    ///
    /// # Arguments
    ///
    /// * `fd` - FD of a media source file.
    ///
    /// * `offset` - Offset of the file to be read.
    ///
    /// * `size` - File size, in bytes
    ///
    /// # Returns
    ///
    /// * Pointer to the **OH_AVMediaSource** instance if the operation is successful; null pointer if the operation
    /// fails.
    ///
    ///
    /// Possible failure causes:
    /// 1. fd is invalid.
    /// 2. offset is invalid.
    /// 3. size error.
    /// 4. resource is invalid.
    /// 5. file format is not supported.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSource_CreateWithFd(fd: i32, offset: i64, size: i64) -> *mut OH_AVMediaSource;
    /// Releases a media source instance.
    ///
    /// # Arguments
    ///
    /// * `source` - Pointer to the **OH_AVMediaSource** instance.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The **source** is a null pointer or fails to be released.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSource_Destroy(source: *mut OH_AVMediaSource) -> OH_AVErrCode;
    /// Sets the MIME type to process extended media sources.
    ///
    /// # Arguments
    ///
    /// * `source` - Pointer to the **OH_AVMediaSource** instance.
    ///
    /// * `mimetype` - Pointer to the MIME type (`AV_MimeTypes`) of the media source.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The **source** or **mimetype** is a null pointer.
    /// [`AV_ERR_UNSUPPORTED_FORMAT`](crate::averrors::OH_AVErrCode::AV_ERR_UNSUPPORTED_FORMAT): The **mimetype** is not supported.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSource_SetMimeType(
        source: *mut OH_AVMediaSource,
        mimetype: *const ::core::ffi::c_char,
    ) -> OH_AVErrCode;
    /// Obtains the URL of a request.
    ///
    /// # Arguments
    ///
    /// * `request` - Pointer to the **OH_AVMediaSourceLoadingRequest** instance.
    ///
    /// * `url` - Double pointer to the URL for output.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The **request** is a null pointer or the URL does not exist.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoadingRequest_GetUrl(
        request: *mut OH_AVMediaSourceLoadingRequest,
        url: *mut *const ::core::ffi::c_char,
    ) -> OH_AVErrCode;
    /// Obtains the HTTP header of a request.
    ///
    /// # Arguments
    ///
    /// * `request` - Pointer to the **OH_AVMediaSourceLoadingRequest** instance.
    ///
    /// * `header` - Double pointer to the HTTP header used for the HTTP request.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The **request** is a null pointer.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoadingRequest_GetHttpHeader(
        request: *mut OH_AVMediaSourceLoadingRequest,
        header: *mut *mut OH_AVHttpHeader,
    ) -> OH_AVErrCode;
    /// Sends request data to the AVPlayer.
    ///
    /// # Arguments
    ///
    /// * `request` - Pointer to the request for opening a resource.
    ///
    /// * `uuid` - ID of the resource handle.
    ///
    /// * `offset` - Offset of the current media data relative to the start of the resource.
    ///
    /// * `data` - Pointer to the media data sent to the player.
    ///
    /// * `dataSize` - Length of the data sent to the player.
    ///
    /// # Returns
    ///
    /// * Number of bytes accepted by the current read operation. If the return value is less than 0, the operation
    /// fails.
    /// The value **-2** indicates that the player no longer needs the current data, and the client should stop the current
    /// read process.
    /// The value **-3** indicates that the player's buffer is full, and the client should wait for the next read.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoadingRequest_RespondData(
        request: *mut OH_AVMediaSourceLoadingRequest,
        uuid: i64,
        offset: i64,
        data: *const u8,
        dataSize: u64,
    ) -> i32;
    /// Sends the response header to the AVPlayer. This API must be called before [`OH_AVMediaSourceLoadingRequest_RespondData`](crate::avmedia_source::OH_AVMediaSourceLoadingRequest_RespondData)
    /// is called for the first time.
    ///
    /// # Arguments
    ///
    /// * `request` - Pointer to the request for opening a resource.
    ///
    /// * `uuid` - ID of the resource handle.
    ///
    /// * `header` - Pointer to the header information in the HTTP response.
    /// The application can intersect the header field with the supported fields at the bottom layer and then pass the
    /// intersection result to the AVPlayer, or directly pass all the corresponding header information.
    ///
    /// * `redirectUrl` - Pointer to the redirection URL contained in the HTTP response (if any).
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoadingRequest_RespondHeader(
        request: *mut OH_AVMediaSourceLoadingRequest,
        uuid: i64,
        header: *mut OH_AVHttpHeader,
        redirectUrl: *const ::core::ffi::c_char,
    );
    /// Notifies the player of the current request status. After pushing all data of a single resource, the
    /// application should send the **LOADING_ERROR_SUCCESS** state to notify the player that the resource push is complete.
    ///
    /// # Arguments
    ///
    /// * `request` - Pointer to the request for opening a resource.
    ///
    /// * `uuid` - ID of the resource handle.
    ///
    /// * `error` - Audio playback is in the error state.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoadingRequest_FinishLoading(
        request: *mut OH_AVMediaSourceLoadingRequest,
        uuid: i64,
        error: AVLoadingRequestError,
    );
    /// Creates an **OH_AVMediaSourceLoader** instance. If the operation is successful, the **OH_AVMediaSourceLoader**
    /// pointer is returned. If the operation fails, a null pointer is returned.
    ///
    ///
    /// # Returns
    ///
    /// * OH_AVMediaSourceLoader pointer if success, else return NULL.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoader_Create() -> *mut OH_AVMediaSourceLoader;
    /// Releases an **OH_AVMediaSourceLoader** instance.
    ///
    /// # Arguments
    ///
    /// * `loader` - Pointer to the **OH_AVMediaSourceLoader** instance to be released.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The **loader** is a null pointer or fails to be released.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoader_Destroy(loader: *mut OH_AVMediaSourceLoader) -> OH_AVErrCode;
    /// Sets a source loader for the media source instance.
    ///
    /// # Arguments
    ///
    /// * `source` - Pointer to the **OH_AVMediaSource** that requires a network proxy.
    ///
    /// * `loader` - Pointer to the **OH_AVMediaSourceLoader** instance.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The **source** or **loader** is a null pointer, or the operation fails.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSource_SetMediaSourceLoader(
        source: *mut OH_AVMediaSource,
        loader: *mut OH_AVMediaSourceLoader,
    ) -> OH_AVErrCode;
    /// Sets the open callback function for **OH_AVMediaSourceLoader**.
    ///
    /// # Arguments
    ///
    /// * `loader` - Pointer to the **OH_AVMediaSourceLoader** instance for which the callback function is to be set.
    ///
    /// * `callback` - Open callback function to be set.
    ///
    /// * `userData` - Pointer to the user-defined data used in the callback function.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The **loader** is a null pointer or the operation fails.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoader_SetSourceOpenCallback(
        loader: *mut OH_AVMediaSourceLoader,
        callback: OH_AVMediaSourceLoaderOnSourceOpenedCallback,
        userData: *mut ::core::ffi::c_void,
    ) -> OH_AVErrCode;
    /// Sets the read callback function for **OH_AVMediaSourceLoader**.
    ///
    /// # Arguments
    ///
    /// * `loader` - Pointer to the **OH_AVMediaSourceLoader** instance for which the callback function is to be set.
    ///
    /// * `callback` - Read callback function to be set.
    ///
    /// * `userData` - Pointer to the user-defined data used in the callback function.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The **loader** is a null pointer or the operation fails.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoader_SetSourceReadCallback(
        loader: *mut OH_AVMediaSourceLoader,
        callback: OH_AVMediaSourceLoaderOnSourceReadCallback,
        userData: *mut ::core::ffi::c_void,
    ) -> OH_AVErrCode;
    /// Sets the close callback function for **OH_AVMediaSourceLoader**.
    ///
    /// # Arguments
    ///
    /// * `loader` - Pointer to the **OH_AVMediaSourceLoader** instance for which the callback function is to be set.
    ///
    /// * `callback` - Close callback function to be set.
    ///
    /// * `userData` - Pointer to the user-defined data used in the callback function.
    ///
    /// # Returns
    ///
    /// * Execution result of the function.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The **loader** is a null pointer or the operation fails.
    ///
    /// Available since API-level: 23
    #[cfg(feature = "api-23")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-23")))]
    pub fn OH_AVMediaSourceLoader_SetSourceCloseCallback(
        loader: *mut OH_AVMediaSourceLoader,
        callback: OH_AVMediaSourceLoaderOnSourceClosedCallback,
        userData: *mut ::core::ffi::c_void,
    ) -> OH_AVErrCode;
}
