// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(deprecated)]
#[allow(unused_imports)]
use crate::averrors::OH_AVErrCode;

#[cfg(feature = "api-18")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
impl OH_AVImageGenerator_QueryOptions {
    /// This option is used to fetch a key frame from the given media
    /// resource that is located right after or at the given time.
    pub const OH_AVIMAGE_GENERATOR_QUERY_NEXT_SYNC: OH_AVImageGenerator_QueryOptions =
        OH_AVImageGenerator_QueryOptions(0);
    /// This option is used to fetch a key frame from the given media
    /// resource that is located right before or at the given time.
    pub const OH_AVIMAGE_GENERATOR_QUERY_PREVIOUS_SYNC: OH_AVImageGenerator_QueryOptions =
        OH_AVImageGenerator_QueryOptions(1);
    /// This option is used to fetch a key frame from the given media
    /// resource that is located closest to or at the given time.
    pub const OH_AVIMAGE_GENERATOR_QUERY_CLOSEST_SYNC: OH_AVImageGenerator_QueryOptions =
        OH_AVImageGenerator_QueryOptions(2);
    /// This option is used to fetch a frame (maybe not keyframe) from
    /// the given media resource that is located closest to or at the given time.
    pub const OH_AVIMAGE_GENERATOR_QUERY_CLOSEST: OH_AVImageGenerator_QueryOptions =
        OH_AVImageGenerator_QueryOptions(3);
}
#[repr(transparent)]
/// Enumerates the image query options about the relationship between the given timeUs and a key frame.
///
///
/// Required System Capabilities: SystemCapability.Multimedia.Media.AVImageGenerator
///
/// Available since API-level: 18
#[cfg(feature = "api-18")]
#[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct OH_AVImageGenerator_QueryOptions(pub ::core::ffi::c_uint);
