pub(crate) static OPAQUE_TYPES: [&str; 14] = [
    "OH_PixelmapNative",
    "NativePixelMap_",
    "OH_NativeBuffer",
    "NativeWindow",
    "NativeWindowBuffer",
    "OHNativeWindow",
    "OHNativeWindowBuffer",
    "ArkUI_AccessibilityProvider",
    "OH_NativeColorSpaceManager",
    "napi_env",
    "napi_env__",
    "napi_value",
    "napi_value__",
    "OH_ImageSourceNative",
];