// automatically generated by rust-bindgen 0.71.1

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(deprecated)]
#[allow(unused_imports)]
use crate::averrors::OH_AVErrCode;
#[cfg(feature = "api-26")]
use crate::avformat::OH_AVFormat;
#[allow(unused_imports)]
use crate::avrecorder_base::{
    OH_AVRecorder, OH_AVRecorder_Config, OH_AVRecorder_EncoderInfo, OH_AVRecorder_OnError,
    OH_AVRecorder_OnStateChange,
};
use ohos_sys_opaque_types::OHNativeWindow;

extern "C" {
    /// Creates an AVRecorder instance. After this function is successfully called, the AVRecorder transitions to the
    /// AVRECORDER_IDLE state.
    ///
    ///
    /// # Returns
    ///
    /// * Pointer to the OH_AVRecorder instance created if the operation is successful; nullptr otherwise.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_Create() -> *mut OH_AVRecorder;
    /// Sets AVRecorder parameters to prepare for recording. This function must be called after [`OH_AVRecorder_Create`](crate::avrecorder::OH_AVRecorder_Create)
    /// is successfully triggered. After this function is successfully called, the AVRecorder transitions to the
    /// AVRECORDER_PREPARED state.
    /// To record only audio, you do not need to set video parameters. Similarly, to record only video, you do not need to
    /// set audio parameters.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// * `config` - Pointer to the OH_AVRecorder_Config instance.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr or the preparation fails.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_Prepare(
        recorder: *mut OH_AVRecorder,
        config: *mut OH_AVRecorder_Config,
    ) -> OH_AVErrCode;
    /// Obtains the AVRecorder configuration. This function must be called after the recording preparation is
    /// complete.
    /// **config** must be set to nullptr. The framework layer allocates and releases the memory in a unified manner to
    /// avoid issues with memory management, such as leaks or double freeing.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// * `config` - Pointer to the OH_AVRecorder_Config instance.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr or **config** is not nullptr.
    /// [`AV_ERR_NO_MEMORY`](crate::averrors::OH_AVErrCode::AV_ERR_NO_MEMORY): The memory fails to be allocated due to insufficient memory.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_GetAVRecorderConfig(
        recorder: *mut OH_AVRecorder,
        config: *mut *mut OH_AVRecorder_Config,
    ) -> OH_AVErrCode;
    /// Obtains an input surface. This function must be called after [`OH_AVRecorder_Prepare`](crate::avrecorder::OH_AVRecorder_Prepare) is successfully triggered and before [`OH_AVRecorder_Start`](crate::avrecorder::OH_AVRecorder_Start)
    /// is called.
    /// The caller obtains the **surfaceBuffer** from this surface and fills in the corresponding video data.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// * `window` - Pointer to the OHNativeWindow instance.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_GetInputSurface(
        recorder: *mut OH_AVRecorder,
        window: *mut *mut OHNativeWindow,
    ) -> OH_AVErrCode;
    /// Updates the video rotation angle. This function must be called after [`OH_AVRecorder_Prepare`](crate::avrecorder::OH_AVRecorder_Prepare) is successfully triggered and before [`OH_AVRecorder_Start`](crate::avrecorder::OH_AVRecorder_Start)
    /// is called.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// * `rotation` - Video rotation angle, in degrees. The value must be an integer in the range \[0, 90, 180, 270\].
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr, **rotation** is invalid, or the update
    /// operation fails.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_UpdateRotation(
        recorder: *mut OH_AVRecorder,
        rotation: i32,
    ) -> OH_AVErrCode;
    /// Starts recording. This function must be called after [`OH_AVRecorder_Prepare`](crate::avrecorder::OH_AVRecorder_Prepare) is successfully triggered.
    /// After this function is successfully called, the AVRecorder transitions to the AVRECORDER_STARTED state.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr or recording fails to start.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_Start(recorder: *mut OH_AVRecorder) -> OH_AVErrCode;
    /// Pauses recording. This function must be called after [`OH_AVRecorder_Start`](crate::avrecorder::OH_AVRecorder_Start) is successfully triggered
    /// and the AVRecorder is in the AVRECORDER_STARTED state. After this function is successfully called, the AVRecorder
    /// transitions to the AVRECORDER_PAUSED state.
    /// Then, you can call [`OH_AVRecorder_Resume`](crate::avrecorder::OH_AVRecorder_Resume) to resume recording, and the AVRecorder transitions the
    /// AVRECORDER_STARTED state again.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr or recording fails to pause.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_Pause(recorder: *mut OH_AVRecorder) -> OH_AVErrCode;
    /// Resumes recording. This function must be called after [`OH_AVRecorder_Pause`](crate::avrecorder::OH_AVRecorder_Pause) is successfully triggered
    /// and the AVRecorder is in the AVRECORDER_PAUSED state. After this function is successfully called, the AVRecorder
    /// transitions to the AVRECORDER_STARTED state.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr or recording fails to resume.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_Resume(recorder: *mut OH_AVRecorder) -> OH_AVErrCode;
    /// Stops recording. This function must be called after [`OH_AVRecorder_Start`](crate::avrecorder::OH_AVRecorder_Start) is successfully triggered.
    /// After this function is successfully called, the AVRecorder transitions to the AVRECORDER_STOPPED state.
    /// For audio-only recording, you can call [`OH_AVRecorder_Prepare`](crate::avrecorder::OH_AVRecorder_Prepare) again for re-recording.
    /// For video-only recording or audio and video recording, you can call [`OH_AVRecorder_Prepare`](crate::avrecorder::OH_AVRecorder_Prepare) and [`OH_AVRecorder_GetInputSurface`](crate::avrecorder::OH_AVRecorder_GetInputSurface)
    /// again for re-recording.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr or recording fails to stop.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_Stop(recorder: *mut OH_AVRecorder) -> OH_AVErrCode;
    /// Resets the recording state. This function must be called when the AVRecorder is not in the
    /// AVRECORDER_RELEASED state. After this function is successfully called, the AVRecorder transitions to the
    /// AVRECORDER_IDLE state.
    /// For audio-only recording, you can call [`OH_AVRecorder_Prepare`](crate::avrecorder::OH_AVRecorder_Prepare) again for re-recording.
    /// For video-only recording or audio and video recording, you can call [`OH_AVRecorder_Prepare`](crate::avrecorder::OH_AVRecorder_Prepare) and [`OH_AVRecorder_GetInputSurface`](crate::avrecorder::OH_AVRecorder_GetInputSurface)
    /// again for re-recording.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr or recording fails to reset.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_Reset(recorder: *mut OH_AVRecorder) -> OH_AVErrCode;
    /// Releases recording resources. After this function is successfully called, the AVRecorder transitions to the
    /// AVRECORDER_RELEASED state.
    /// The recorder memory will be released. The application layer must explicitly set the recorder to nullptr to avoid
    /// access to wild pointers. After the resources are released, you can no longer perform any operation on the
    /// OH_AVRecorder instance.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr or recording fails to release.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_Release(recorder: *mut OH_AVRecorder) -> OH_AVErrCode;
    /// Obtains the available encoders and encoder information of the AVRecorder.
    /// **info** must be set to nullptr. The framework layer allocates and releases the memory in a unified manner to avoid
    /// issues with memory management, such as leaks or double freeing.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// * `info` - Pointer to the OH_AVRecorder_EncoderInfo instance.
    ///
    /// * `length` - Pointer to the number of available encoders.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** is nullptr.
    /// [`AV_ERR_NO_MEMORY`](crate::averrors::OH_AVErrCode::AV_ERR_NO_MEMORY): The memory fails to be allocated due to insufficient memory.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_GetAvailableEncoder(
        recorder: *mut OH_AVRecorder,
        info: *mut *mut OH_AVRecorder_EncoderInfo,
        length: *mut i32,
    ) -> OH_AVErrCode;
    /// Sets a state callback so that the application can respond to state change events generated by the AVRecorder.
    /// This function must be called before [`OH_AVRecorder_Start`](crate::avrecorder::OH_AVRecorder_Start) is called.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// * `callback` - Status callback function.
    ///
    /// * `userData` - Pointer to user-defined data.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** or **callback** is nullptr.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_SetStateCallback(
        recorder: *mut OH_AVRecorder,
        callback: OH_AVRecorder_OnStateChange,
        userData: *mut ::core::ffi::c_void,
    ) -> OH_AVErrCode;
    /// Sets an error callback so that the application can respond to error events generated by the AVRecorder. This
    /// function must be called before [`OH_AVRecorder_Start`](crate::avrecorder::OH_AVRecorder_Start) is called.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// * `callback` - Error callback function.
    ///
    /// * `userData` - Pointer to user-defined data.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** or **callback** is nullptr.
    ///
    /// Available since API-level: 18
    #[cfg(feature = "api-18")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-18")))]
    pub fn OH_AVRecorder_SetErrorCallback(
        recorder: *mut OH_AVRecorder,
        callback: OH_AVRecorder_OnError,
        userData: *mut ::core::ffi::c_void,
    ) -> OH_AVErrCode;
    /// Sets whether to enable the mute interruption mode.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to the OH_AVRecorder instance.
    ///
    /// * `muteWhenInterrupted` - Sets whether to enable the mute interruption mode. The value **true** indicates that the
    /// application remains muted instead of being interrupted when recording is required. The value **false** indicates
    /// that the application stops recording instead of remain muted when the recording is interrupted.
    ///
    /// # Returns
    ///
    /// * [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): The operation is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): The input parameter **recorder** or **callback** is nullptr.
    /// [`AV_ERR_INVALID_STATE`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_STATE): The function is called in an invalid state. It must be in the prepared state.
    ///
    /// Available since API-level: 20
    #[cfg(feature = "api-20")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-20")))]
    pub fn OH_AVRecorder_SetWillMuteWhenInterrupted(
        recorder: *mut OH_AVRecorder,
        muteWhenInterrupted: bool,
    ) -> OH_AVErrCode;
    /// Obtains the maximum amplitude of the current audio capturer.
    /// The amplitude value is the max value from the last call to the current call.
    /// For example, if you have obtained the maximum amplitude at 1s, and you call this API again at 2s,
    /// then the return value is the maximum amplitude within the duration from 1s to 2s.
    ///
    /// This API can be called only after the **prepare()** API is called.
    /// If this API is called after **stop()** is successfully called, an error is reported.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to an OH_AVRecorder instance
    ///
    /// * `amplitude` - The max amplitude value of audio capturer
    ///
    /// # Returns
    ///
    /// * Function result code.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): the execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): input recorder is nullptr or amplitude is nullptr.
    /// [`AV_ERR_INVALID_STATE`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_STATE): function called in invalid state.
    /// [`AV_ERR_NO_MEMORY`](crate::averrors::OH_AVErrCode::AV_ERR_NO_MEMORY): failed to malloc memory.
    /// [`AV_ERR_UNKNOWN`](crate::averrors::OH_AVErrCode::AV_ERR_UNKNOWN): unknown error.
    ///
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AVRecorder_GetAudioCapturerMaxAmplitude(
        recorder: *mut OH_AVRecorder,
        amplitude: *mut i32,
    ) -> OH_AVErrCode;
    /// Set metadata (key-value pairs) for the recording file of the recorder.
    /// This metadata overwrites the value in config.metadata.customInfo (see {prepare()} and {OH_AVRecorder_Config})
    /// if they have same key.
    /// This API can be called only after the **prepare()** API is called, before stop recorder.
    ///
    /// # Arguments
    ///
    /// * `recorder` - Pointer to an OH_AVRecorder instance
    ///
    /// * `metadata` - The key-value pairs added to the the recording file.
    /// The key string should start with "com.openharmony.",
    /// the length of value can't be more than 256 bytes.
    ///
    /// # Returns
    ///
    /// * Function result code.
    /// [`AV_ERR_OK`](crate::averrors::OH_AVErrCode::AV_ERR_OK): the execution is successful.
    /// [`AV_ERR_INVALID_VAL`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_VAL): input recorder is nullptr or metadata is nullptr
    /// or the length of value exceed max length.
    /// [`AV_ERR_INVALID_STATE`](crate::averrors::OH_AVErrCode::AV_ERR_INVALID_STATE): function called in invalid state.
    /// [`AV_ERR_NO_MEMORY`](crate::averrors::OH_AVErrCode::AV_ERR_NO_MEMORY): failed to malloc memory.
    /// [`AV_ERR_UNKNOWN`](crate::averrors::OH_AVErrCode::AV_ERR_UNKNOWN): unknown error.
    ///
    ///
    /// Available since API-level: 26
    #[cfg(feature = "api-26")]
    #[cfg_attr(docsrs, doc(cfg(feature = "api-26")))]
    pub fn OH_AVRecorder_SetMetadata(
        recorder: *mut OH_AVRecorder,
        metadata: *const OH_AVFormat,
    ) -> OH_AVErrCode;
}
