#[link(name = "native_drawing")]
extern "C" {}

pub mod bitmap;
pub mod brush;
pub mod canvas;
pub mod color;
pub mod font_collection;
pub mod path;
pub mod pen;
pub mod text_declaration;
pub mod text_typography;
pub mod types;

#[cfg(feature = "api-11")]
pub mod color_filter;
#[cfg(feature = "api-11")]
pub mod filter;
#[cfg(feature = "api-11")]
pub mod font;
#[cfg(feature = "api-11")]
pub mod mask_filter;
#[cfg(feature = "api-11")]
pub mod matrix;
#[cfg(feature = "api-11")]
pub mod point;
#[cfg(feature = "api-11")]
pub mod rect;
#[cfg(feature = "api-11")]
pub mod register_font;
#[cfg(feature = "api-11")]
pub mod round_rect;
#[cfg(feature = "api-11")]
pub mod shader_effect;
#[cfg(feature = "api-11")]
pub mod text_blob;
#[cfg(feature = "api-11")]
pub mod typeface;
